package fleet.model;

import oracle.jbo.client.Configuration;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 30 15:43:42 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleFleetImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleFleetImpl() {
    }

    /**
     * Container's getter for BookingStatusView1.
     * @return BookingStatusView1
     */
    public ViewObjectImpl getBookingStatusView1() {
        return (ViewObjectImpl) findViewObject("BookingStatusView1");
    }

    /**
     * Container's getter for BookingTypesView1.
     * @return BookingTypesView1
     */
    public ViewObjectImpl getBookingTypesView1() {
        return (ViewObjectImpl) findViewObject("BookingTypesView1");
    }

    /**
     * Container's getter for BookingsView1.
     * @return BookingsView1
     */
    public BookingsViewImpl getBookingsView1() {
        return (BookingsViewImpl) findViewObject("BookingsView1");
    }

    /**
     * Container's getter for DriversView1.
     * @return DriversView1
     */
    public ViewObjectImpl getDriversView1() {
        return (ViewObjectImpl) findViewObject("DriversView1");
    }

    /**
     * Container's getter for RefillsView1.
     * @return RefillsView1
     */
    public ViewObjectImpl getRefillsView1() {
        return (ViewObjectImpl) findViewObject("RefillsView1");
    }

    /**
     * Container's getter for RolesView1.
     * @return RolesView1
     */
    public ViewObjectImpl getRolesView1() {
        return (ViewObjectImpl) findViewObject("RolesView1");
    }

    /**
     * Container's getter for TransportItemsView1.
     * @return TransportItemsView1
     */
    public ViewObjectImpl getTransportItemsView1() {
        return (ViewObjectImpl) findViewObject("TransportItemsView1");
    }

    /**
     * Container's getter for TripsView1.
     * @return TripsView1
     */
    public ViewObjectImpl getTripsView1() {
        return (ViewObjectImpl) findViewObject("TripsView1");
    }

    /**
     * Container's getter for UnitsView1.
     * @return UnitsView1
     */
    public ViewObjectImpl getUnitsView1() {
        return (ViewObjectImpl) findViewObject("UnitsView1");
    }

    /**
     * Container's getter for UsersView1.
     * @return UsersView1
     */
    public UsersViewImpl getUsersView1() {
        return (UsersViewImpl) findViewObject("UsersView1");
    }

    /**
     * Container's getter for VehiclesView1.
     * @return VehiclesView1
     */
    public ViewObjectImpl getVehiclesView1() {
        return (ViewObjectImpl) findViewObject("VehiclesView1");
    }

    /**
     * Container's getter for BookingsView2.
     * @return BookingsView2
     */
    public BookingsViewImpl getBookingsView2() {
        return (BookingsViewImpl) findViewObject("BookingsView2");
    }

    /**
     * Container's getter for BookingsView3.
     * @return BookingsView3
     */
    public BookingsViewImpl getBookingsView3() {
        return (BookingsViewImpl) findViewObject("BookingsView3");
    }

    /**
     * Container's getter for BookingsView4.
     * @return BookingsView4
     */
    public BookingsViewImpl getBookingsView4() {
        return (BookingsViewImpl) findViewObject("BookingsView4");
    }

    /**
     * Container's getter for BookingsView5.
     * @return BookingsView5
     */
    public BookingsViewImpl getBookingsView5() {
        return (BookingsViewImpl) findViewObject("BookingsView5");
    }

    /**
     * Container's getter for BookingsView6.
     * @return BookingsView6
     */
    public BookingsViewImpl getBookingsView6() {
        return (BookingsViewImpl) findViewObject("BookingsView6");
    }

    /**
     * Container's getter for BookingsView7.
     * @return BookingsView7
     */
    public BookingsViewImpl getBookingsView7() {
        return (BookingsViewImpl) findViewObject("BookingsView7");
    }

    /**
     * Container's getter for BookingsView8.
     * @return BookingsView8
     */
    public BookingsViewImpl getBookingsView8() {
        return (BookingsViewImpl) findViewObject("BookingsView8");
    }

    /**
     * Container's getter for BookingsView9.
     * @return BookingsView9
     */
    public BookingsViewImpl getBookingsView9() {
        return (BookingsViewImpl) findViewObject("BookingsView9");
    }

    /**
     * Container's getter for BookingsView10.
     * @return BookingsView10
     */
    public BookingsViewImpl getBookingsView10() {
        return (BookingsViewImpl) findViewObject("BookingsView10");
    }

    /**
     * Container's getter for BookingsView11.
     * @return BookingsView11
     */
    public BookingsViewImpl getBookingsView11() {
        return (BookingsViewImpl) findViewObject("BookingsView11");
    }

    /**
     * Container's getter for BookingsView12.
     * @return BookingsView12
     */
    public BookingsViewImpl getBookingsView12() {
        return (BookingsViewImpl) findViewObject("BookingsView12");
    }

    /**
     * Container's getter for BookingsView13.
     * @return BookingsView13
     */
    public BookingsViewImpl getBookingsView13() {
        return (BookingsViewImpl) findViewObject("BookingsView13");
    }

    /**
     * Container's getter for BookingsView14.
     * @return BookingsView14
     */
    public BookingsViewImpl getBookingsView14() {
        return (BookingsViewImpl) findViewObject("BookingsView14");
    }

    /**
     * Container's getter for BookingsView15.
     * @return BookingsView15
     */
    public BookingsViewImpl getBookingsView15() {
        return (BookingsViewImpl) findViewObject("BookingsView15");
    }

    /**
     * Container's getter for BookingsView16.
     * @return BookingsView16
     */
    public BookingsViewImpl getBookingsView16() {
        return (BookingsViewImpl) findViewObject("BookingsView16");
    }

    /**
     * Container's getter for BookingsView17.
     * @return BookingsView17
     */
    public BookingsViewImpl getBookingsView17() {
        return (BookingsViewImpl) findViewObject("BookingsView17");
    }

    /**
     * Container's getter for RefillsView2.
     * @return RefillsView2
     */
    public ViewObjectImpl getRefillsView2() {
        return (ViewObjectImpl) findViewObject("RefillsView2");
    }

    /**
     * Container's getter for BookingsView18.
     * @return BookingsView18
     */
    public BookingsViewImpl getBookingsView18() {
        return (BookingsViewImpl) findViewObject("BookingsView18");
    }

    /**
     * Container's getter for BookingsView19.
     * @return BookingsView19
     */
    public BookingsViewImpl getBookingsView19() {
        return (BookingsViewImpl) findViewObject("BookingsView19");
    }

    /**
     * Container's getter for BookingsView20.
     * @return BookingsView20
     */
    public BookingsViewImpl getBookingsView20() {
        return (BookingsViewImpl) findViewObject("BookingsView20");
    }

    /**
     * Container's getter for BookingsView21.
     * @return BookingsView21
     */
    public BookingsViewImpl getBookingsView21() {
        return (BookingsViewImpl) findViewObject("BookingsView21");
    }

    /**
     * Container's getter for RefillsView3.
     * @return RefillsView3
     */
    public ViewObjectImpl getRefillsView3() {
        return (ViewObjectImpl) findViewObject("RefillsView3");
    }

    /**
     * Container's getter for RefillsView4.
     * @return RefillsView4
     */
    public ViewObjectImpl getRefillsView4() {
        return (ViewObjectImpl) findViewObject("RefillsView4");
    }

    /**
     * Container's getter for RefillsView5.
     * @return RefillsView5
     */
    public ViewObjectImpl getRefillsView5() {
        return (ViewObjectImpl) findViewObject("RefillsView5");
    }

    /**
     * Container's getter for RefillsView6.
     * @return RefillsView6
     */
    public ViewObjectImpl getRefillsView6() {
        return (ViewObjectImpl) findViewObject("RefillsView6");
    }

    /**
     * Container's getter for RefillsView7.
     * @return RefillsView7
     */
    public ViewObjectImpl getRefillsView7() {
        return (ViewObjectImpl) findViewObject("RefillsView7");
    }

    /**
     * Container's getter for BookingsView22.
     * @return BookingsView22
     */
    public BookingsViewImpl getBookingsView22() {
        return (BookingsViewImpl) findViewObject("BookingsView22");
    }

    /**
     * Container's getter for BookingsView23.
     * @return BookingsView23
     */
    public BookingsViewImpl getBookingsView23() {
        return (BookingsViewImpl) findViewObject("BookingsView23");
    }

    /**
     * Container's getter for BookingsView24.
     * @return BookingsView24
     */
    public BookingsViewImpl getBookingsView24() {
        return (BookingsViewImpl) findViewObject("BookingsView24");
    }

    /**
     * Container's getter for BookingsView25.
     * @return BookingsView25
     */
    public BookingsViewImpl getBookingsView25() {
        return (BookingsViewImpl) findViewObject("BookingsView25");
    }

    /**
     * Container's getter for RefillsView8.
     * @return RefillsView8
     */
    public ViewObjectImpl getRefillsView8() {
        return (ViewObjectImpl) findViewObject("RefillsView8");
    }

    /**
     * Container's getter for BookingsView26.
     * @return BookingsView26
     */
    public BookingsViewImpl getBookingsView26() {
        return (BookingsViewImpl) findViewObject("BookingsView26");
    }

    /**
     * Container's getter for BookingsView27.
     * @return BookingsView27
     */
    public BookingsViewImpl getBookingsView27() {
        return (BookingsViewImpl) findViewObject("BookingsView27");
    }

    /**
     * Container's getter for BookingsView28.
     * @return BookingsView28
     */
    public BookingsViewImpl getBookingsView28() {
        return (BookingsViewImpl) findViewObject("BookingsView28");
    }

    /**
     * Container's getter for BookingsView29.
     * @return BookingsView29
     */
    public BookingsViewImpl getBookingsView29() {
        return (BookingsViewImpl) findViewObject("BookingsView29");
    }

    /**
     * Container's getter for TripsView2.
     * @return TripsView2
     */
    public ViewObjectImpl getTripsView2() {
        return (ViewObjectImpl) findViewObject("TripsView2");
    }

    /**
     * Container's getter for TripsView3.
     * @return TripsView3
     */
    public ViewObjectImpl getTripsView3() {
        return (ViewObjectImpl) findViewObject("TripsView3");
    }

    /**
     * Container's getter for TripsView4.
     * @return TripsView4
     */
    public ViewObjectImpl getTripsView4() {
        return (ViewObjectImpl) findViewObject("TripsView4");
    }

    /**
     * Container's getter for RefillsView9.
     * @return RefillsView9
     */
    public ViewObjectImpl getRefillsView9() {
        return (ViewObjectImpl) findViewObject("RefillsView9");
    }

    /**
     * Container's getter for BookingsView30.
     * @return BookingsView30
     */
    public BookingsViewImpl getBookingsView30() {
        return (BookingsViewImpl) findViewObject("BookingsView30");
    }

    /**
     * Container's getter for BookingsView31.
     * @return BookingsView31
     */
    public BookingsViewImpl getBookingsView31() {
        return (BookingsViewImpl) findViewObject("BookingsView31");
    }

    /**
     * Container's getter for BookingsView32.
     * @return BookingsView32
     */
    public BookingsViewImpl getBookingsView32() {
        return (BookingsViewImpl) findViewObject("BookingsView32");
    }

    /**
     * Container's getter for BookingsView33.
     * @return BookingsView33
     */
    public BookingsViewImpl getBookingsView33() {
        return (BookingsViewImpl) findViewObject("BookingsView33");
    }

    /**
     * Container's getter for TripsView5.
     * @return TripsView5
     */
    public ViewObjectImpl getTripsView5() {
        return (ViewObjectImpl) findViewObject("TripsView5");
    }

    /**
     * Container's getter for TripsView6.
     * @return TripsView6
     */
    public ViewObjectImpl getTripsView6() {
        return (ViewObjectImpl) findViewObject("TripsView6");
    }

    /**
     * Container's getter for TripsView7.
     * @return TripsView7
     */
    public ViewObjectImpl getTripsView7() {
        return (ViewObjectImpl) findViewObject("TripsView7");
    }

    /**
     * Container's getter for TripsView8.
     * @return TripsView8
     */
    public ViewObjectImpl getTripsView8() {
        return (ViewObjectImpl) findViewObject("TripsView8");
    }

    /**
     * Container's getter for TripsView9.
     * @return TripsView9
     */
    public ViewObjectImpl getTripsView9() {
        return (ViewObjectImpl) findViewObject("TripsView9");
    }

    /**
     * Container's getter for TripsView10.
     * @return TripsView10
     */
    public ViewObjectImpl getTripsView10() {
        return (ViewObjectImpl) findViewObject("TripsView10");
    }

    /**
     * Container's getter for TripsView11.
     * @return TripsView11
     */
    public ViewObjectImpl getTripsView11() {
        return (ViewObjectImpl) findViewObject("TripsView11");
    }

    /**
     * Container's getter for TripsView12.
     * @return TripsView12
     */
    public ViewObjectImpl getTripsView12() {
        return (ViewObjectImpl) findViewObject("TripsView12");
    }

    /**
     * Container's getter for TripsView13.
     * @return TripsView13
     */
    public ViewObjectImpl getTripsView13() {
        return (ViewObjectImpl) findViewObject("TripsView13");
    }

    /**
     * Container's getter for TripsView14.
     * @return TripsView14
     */
    public ViewObjectImpl getTripsView14() {
        return (ViewObjectImpl) findViewObject("TripsView14");
    }

    /**
     * Container's getter for TripsView15.
     * @return TripsView15
     */
    public ViewObjectImpl getTripsView15() {
        return (ViewObjectImpl) findViewObject("TripsView15");
    }

    /**
     * Container's getter for TripsView16.
     * @return TripsView16
     */
    public ViewObjectImpl getTripsView16() {
        return (ViewObjectImpl) findViewObject("TripsView16");
    }

    /**
     * Container's getter for TripsView17.
     * @return TripsView17
     */
    public ViewObjectImpl getTripsView17() {
        return (ViewObjectImpl) findViewObject("TripsView17");
    }

    /**
     * Container's getter for TripsView18.
     * @return TripsView18
     */
    public ViewObjectImpl getTripsView18() {
        return (ViewObjectImpl) findViewObject("TripsView18");
    }

    /**
     * Container's getter for TripsView19.
     * @return TripsView19
     */
    public ViewObjectImpl getTripsView19() {
        return (ViewObjectImpl) findViewObject("TripsView19");
    }

    /**
     * Container's getter for TripsView20.
     * @return TripsView20
     */
    public ViewObjectImpl getTripsView20() {
        return (ViewObjectImpl) findViewObject("TripsView20");
    }

    /**
     * Container's getter for TripsView21.
     * @return TripsView21
     */
    public ViewObjectImpl getTripsView21() {
        return (ViewObjectImpl) findViewObject("TripsView21");
    }

    /**
     * Container's getter for TripsView22.
     * @return TripsView22
     */
    public ViewObjectImpl getTripsView22() {
        return (ViewObjectImpl) findViewObject("TripsView22");
    }

    /**
     * Container's getter for TripsView23.
     * @return TripsView23
     */
    public ViewObjectImpl getTripsView23() {
        return (ViewObjectImpl) findViewObject("TripsView23");
    }

    /**
     * Container's getter for TripsView24.
     * @return TripsView24
     */
    public ViewObjectImpl getTripsView24() {
        return (ViewObjectImpl) findViewObject("TripsView24");
    }

    /**
     * Container's getter for TripsView25.
     * @return TripsView25
     */
    public ViewObjectImpl getTripsView25() {
        return (ViewObjectImpl) findViewObject("TripsView25");
    }

    /**
     * Container's getter for TripsView26.
     * @return TripsView26
     */
    public ViewObjectImpl getTripsView26() {
        return (ViewObjectImpl) findViewObject("TripsView26");
    }

    /**
     * Container's getter for TripsView27.
     * @return TripsView27
     */
    public ViewObjectImpl getTripsView27() {
        return (ViewObjectImpl) findViewObject("TripsView27");
    }

    /**
     * Container's getter for TripsView28.
     * @return TripsView28
     */
    public ViewObjectImpl getTripsView28() {
        return (ViewObjectImpl) findViewObject("TripsView28");
    }

    /**
     * Container's getter for RefillsView10.
     * @return RefillsView10
     */
    public ViewObjectImpl getRefillsView10() {
        return (ViewObjectImpl) findViewObject("RefillsView10");
    }

    /**
     * Container's getter for BookingsView34.
     * @return BookingsView34
     */
    public BookingsViewImpl getBookingsView34() {
        return (BookingsViewImpl) findViewObject("BookingsView34");
    }

    /**
     * Container's getter for BookingsView35.
     * @return BookingsView35
     */
    public BookingsViewImpl getBookingsView35() {
        return (BookingsViewImpl) findViewObject("BookingsView35");
    }

    /**
     * Container's getter for BookingsView36.
     * @return BookingsView36
     */
    public BookingsViewImpl getBookingsView36() {
        return (BookingsViewImpl) findViewObject("BookingsView36");
    }

    /**
     * Container's getter for BookingsView37.
     * @return BookingsView37
     */
    public BookingsViewImpl getBookingsView37() {
        return (BookingsViewImpl) findViewObject("BookingsView37");
    }

    /**
     * Container's getter for TripsView29.
     * @return TripsView29
     */
    public ViewObjectImpl getTripsView29() {
        return (ViewObjectImpl) findViewObject("TripsView29");
    }

    /**
     * Container's getter for TripsView30.
     * @return TripsView30
     */
    public ViewObjectImpl getTripsView30() {
        return (ViewObjectImpl) findViewObject("TripsView30");
    }

    /**
     * Container's getter for TripsView31.
     * @return TripsView31
     */
    public ViewObjectImpl getTripsView31() {
        return (ViewObjectImpl) findViewObject("TripsView31");
    }

    /**
     * Container's getter for RefillsView11.
     * @return RefillsView11
     */
    public ViewObjectImpl getRefillsView11() {
        return (ViewObjectImpl) findViewObject("RefillsView11");
    }

    /**
     * Container's getter for BookingsView38.
     * @return BookingsView38
     */
    public BookingsViewImpl getBookingsView38() {
        return (BookingsViewImpl) findViewObject("BookingsView38");
    }

    /**
     * Container's getter for BookingsView39.
     * @return BookingsView39
     */
    public BookingsViewImpl getBookingsView39() {
        return (BookingsViewImpl) findViewObject("BookingsView39");
    }

    /**
     * Container's getter for BookingsView40.
     * @return BookingsView40
     */
    public BookingsViewImpl getBookingsView40() {
        return (BookingsViewImpl) findViewObject("BookingsView40");
    }

    /**
     * Container's getter for BookingsView41.
     * @return BookingsView41
     */
    public BookingsViewImpl getBookingsView41() {
        return (BookingsViewImpl) findViewObject("BookingsView41");
    }

    /**
     * Container's getter for UsersView2.
     * @return UsersView2
     */
    public UsersViewImpl getUsersView2() {
        return (UsersViewImpl) findViewObject("UsersView2");
    }

    /**
     * Container's getter for UsersView3.
     * @return UsersView3
     */
    public UsersViewImpl getUsersView3() {
        return (UsersViewImpl) findViewObject("UsersView3");
    }

    /**
     * Container's getter for UsersView4.
     * @return UsersView4
     */
    public UsersViewImpl getUsersView4() {
        return (UsersViewImpl) findViewObject("UsersView4");
    }

    /**
     * Container's getter for UsersView5.
     * @return UsersView5
     */
    public UsersViewImpl getUsersView5() {
        return (UsersViewImpl) findViewObject("UsersView5");
    }

    /**
     * Container's getter for UsersView6.
     * @return UsersView6
     */
    public UsersViewImpl getUsersView6() {
        return (UsersViewImpl) findViewObject("UsersView6");
    }

    /**
     * Container's getter for UsersView7.
     * @return UsersView7
     */
    public UsersViewImpl getUsersView7() {
        return (UsersViewImpl) findViewObject("UsersView7");
    }

    /**
     * Container's getter for UsersView8.
     * @return UsersView8
     */
    public UsersViewImpl getUsersView8() {
        return (UsersViewImpl) findViewObject("UsersView8");
    }

    /**
     * Container's getter for UsersView9.
     * @return UsersView9
     */
    public UsersViewImpl getUsersView9() {
        return (UsersViewImpl) findViewObject("UsersView9");
    }

    /**
     * Container's getter for UsersView10.
     * @return UsersView10
     */
    public UsersViewImpl getUsersView10() {
        return (UsersViewImpl) findViewObject("UsersView10");
    }

    /**
     * Container's getter for UsersView11.
     * @return UsersView11
     */
    public UsersViewImpl getUsersView11() {
        return (UsersViewImpl) findViewObject("UsersView11");
    }

    /**
     * Container's getter for UsersView12.
     * @return UsersView12
     */
    public UsersViewImpl getUsersView12() {
        return (UsersViewImpl) findViewObject("UsersView12");
    }

    /**
     * Container's getter for UsersView13.
     * @return UsersView13
     */
    public UsersViewImpl getUsersView13() {
        return (UsersViewImpl) findViewObject("UsersView13");
    }

    /**
     * Container's getter for UsersView14.
     * @return UsersView14
     */
    public UsersViewImpl getUsersView14() {
        return (UsersViewImpl) findViewObject("UsersView14");
    }

    /**
     * Container's getter for UsersView15.
     * @return UsersView15
     */
    public UsersViewImpl getUsersView15() {
        return (UsersViewImpl) findViewObject("UsersView15");
    }

    /**
     * Container's getter for UsersView16.
     * @return UsersView16
     */
    public UsersViewImpl getUsersView16() {
        return (UsersViewImpl) findViewObject("UsersView16");
    }

    /**
     * Container's getter for UsersView17.
     * @return UsersView17
     */
    public UsersViewImpl getUsersView17() {
        return (UsersViewImpl) findViewObject("UsersView17");
    }

    /**
     * Container's getter for UsersView18.
     * @return UsersView18
     */
    public UsersViewImpl getUsersView18() {
        return (UsersViewImpl) findViewObject("UsersView18");
    }

    /**
     * Container's getter for UsersView19.
     * @return UsersView19
     */
    public UsersViewImpl getUsersView19() {
        return (UsersViewImpl) findViewObject("UsersView19");
    }

    /**
     * Container's getter for UsersView20.
     * @return UsersView20
     */
    public UsersViewImpl getUsersView20() {
        return (UsersViewImpl) findViewObject("UsersView20");
    }

    /**
     * Container's getter for UsersView21.
     * @return UsersView21
     */
    public UsersViewImpl getUsersView21() {
        return (UsersViewImpl) findViewObject("UsersView21");
    }

    /**
     * Container's getter for TripsView32.
     * @return TripsView32
     */
    public ViewObjectImpl getTripsView32() {
        return (ViewObjectImpl) findViewObject("TripsView32");
    }

    /**
     * Container's getter for TripsView33.
     * @return TripsView33
     */
    public ViewObjectImpl getTripsView33() {
        return (ViewObjectImpl) findViewObject("TripsView33");
    }

    /**
     * Container's getter for TripsView34.
     * @return TripsView34
     */
    public ViewObjectImpl getTripsView34() {
        return (ViewObjectImpl) findViewObject("TripsView34");
    }

    /**
     * Container's getter for RefillsView12.
     * @return RefillsView12
     */
    public ViewObjectImpl getRefillsView12() {
        return (ViewObjectImpl) findViewObject("RefillsView12");
    }

    /**
     * Container's getter for BookingsView42.
     * @return BookingsView42
     */
    public BookingsViewImpl getBookingsView42() {
        return (BookingsViewImpl) findViewObject("BookingsView42");
    }

    /**
     * Container's getter for BookingsView43.
     * @return BookingsView43
     */
    public BookingsViewImpl getBookingsView43() {
        return (BookingsViewImpl) findViewObject("BookingsView43");
    }

    /**
     * Container's getter for BookingsView44.
     * @return BookingsView44
     */
    public BookingsViewImpl getBookingsView44() {
        return (BookingsViewImpl) findViewObject("BookingsView44");
    }

    /**
     * Container's getter for BookingsView45.
     * @return BookingsView45
     */
    public BookingsViewImpl getBookingsView45() {
        return (BookingsViewImpl) findViewObject("BookingsView45");
    }

    /**
     * Container's getter for UsersView22.
     * @return UsersView22
     */
    public UsersViewImpl getUsersView22() {
        return (UsersViewImpl) findViewObject("UsersView22");
    }

    /**
     * Container's getter for UsersView23.
     * @return UsersView23
     */
    public UsersViewImpl getUsersView23() {
        return (UsersViewImpl) findViewObject("UsersView23");
    }

    /**
     * Container's getter for FkBookingsUsersLink1.
     * @return FkBookingsUsersLink1
     */
    public ViewLinkImpl getFkBookingsUsersLink1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersLink1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsLink1.
     * @return FkBookingsTransportItemsLink1
     */
    public ViewLinkImpl getFkBookingsTransportItemsLink1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsLink1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesLink1.
     * @return FkBookingsBookingTypesLink1
     */
    public ViewLinkImpl getFkBookingsBookingTypesLink1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesLink1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusLink1.
     * @return FkBookingsBookingStatusLink1
     */
    public ViewLinkImpl getFkBookingsBookingStatusLink1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusLink1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc1Link1.
     * @return FkBookingsBookingStatusAssoc1Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc1Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc2Link1.
     * @return FkBookingsBookingStatusAssoc2Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc2Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc1Link1.
     * @return FkBookingsBookingTypesAssoc1Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc1Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc2Link1.
     * @return FkBookingsBookingTypesAssoc2Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc2Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc1Link1.
     * @return FkBookingsTransportItemsAssoc1Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc1Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc2Link1.
     * @return FkBookingsTransportItemsAssoc2Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc2Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc1Link1.
     * @return FkBookingsUsersAssoc1Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc1Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc2Link1.
     * @return FkBookingsUsersAssoc2Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc2Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc3Link1.
     * @return FkBookingsUsersAssoc3Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc3Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc3Link1.
     * @return FkBookingsTransportItemsAssoc3Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc3Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc3Link1.
     * @return FkBookingsBookingTypesAssoc3Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc3Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc3Link1.
     * @return FkBookingsBookingStatusAssoc3Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc3Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesLink1.
     * @return FkRefillsVehiclesLink1
     */
    public ViewLinkImpl getFkRefillsVehiclesLink1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesLink1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc4Link1.
     * @return FkBookingsUsersAssoc4Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc4Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc4Link1.
     * @return FkBookingsTransportItemsAssoc4Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc4Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc4Link1.
     * @return FkBookingsBookingTypesAssoc4Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc4Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc4Link1.
     * @return FkBookingsBookingStatusAssoc4Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc4Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc1Link1.
     * @return FkRefillsVehiclesAssoc1Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc1Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc2Link1.
     * @return FkRefillsVehiclesAssoc2Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc2Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc3Link1.
     * @return FkRefillsVehiclesAssoc3Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc3Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc4Link1.
     * @return FkRefillsVehiclesAssoc4Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc4Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc5Link1.
     * @return FkRefillsVehiclesAssoc5Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc5Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc5Link1.
     * @return FkBookingsUsersAssoc5Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc5Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc5Link1.
     * @return FkBookingsTransportItemsAssoc5Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc5Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc5Link1.
     * @return FkBookingsBookingTypesAssoc5Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc5Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc5Link1.
     * @return FkBookingsBookingStatusAssoc5Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc5Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc6Link1.
     * @return FkRefillsVehiclesAssoc6Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc6Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc6Link1.
     * @return FkBookingsUsersAssoc6Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc6Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc6Link1.
     * @return FkBookingsTransportItemsAssoc6Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc6Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc6Link1.
     * @return FkBookingsBookingTypesAssoc6Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc6Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc6Link1.
     * @return FkBookingsBookingStatusAssoc6Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc6Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesLink1.
     * @return FkTripsVehiclesLink1
     */
    public ViewLinkImpl getFkTripsVehiclesLink1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesLink1");
    }

    /**
     * Container's getter for FkTripsDriversLink1.
     * @return FkTripsDriversLink1
     */
    public ViewLinkImpl getFkTripsDriversLink1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversLink1");
    }

    /**
     * Container's getter for FkTripsBookingsLink1.
     * @return FkTripsBookingsLink1
     */
    public ViewLinkImpl getFkTripsBookingsLink1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsLink1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc7Link1.
     * @return FkRefillsVehiclesAssoc7Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc7Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc7Link1.
     * @return FkBookingsUsersAssoc7Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc7Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc7Link1.
     * @return FkBookingsTransportItemsAssoc7Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc7Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc7Link1.
     * @return FkBookingsBookingTypesAssoc7Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc7Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc7Link1.
     * @return FkBookingsBookingStatusAssoc7Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc7Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc1Link1.
     * @return FkTripsBookingsAssoc1Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc1Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc2Link1.
     * @return FkTripsBookingsAssoc2Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc2Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc3Link1.
     * @return FkTripsBookingsAssoc3Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc3Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc4Link1.
     * @return FkTripsBookingsAssoc4Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc4Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc5Link1.
     * @return FkTripsBookingsAssoc5Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc5Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc6Link1.
     * @return FkTripsBookingsAssoc6Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc6Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc7Link1.
     * @return FkTripsBookingsAssoc7Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc7Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc1Link1.
     * @return FkTripsDriversAssoc1Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc1Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc2Link1.
     * @return FkTripsDriversAssoc2Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc2Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc3Link1.
     * @return FkTripsDriversAssoc3Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc3Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc4Link1.
     * @return FkTripsDriversAssoc4Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc4Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc5Link1.
     * @return FkTripsDriversAssoc5Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc5Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc6Link1.
     * @return FkTripsDriversAssoc6Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc6Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc7Link1.
     * @return FkTripsDriversAssoc7Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc7Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc1Link1.
     * @return FkTripsVehiclesAssoc1Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc1Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc2Link1.
     * @return FkTripsVehiclesAssoc2Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc2Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc3Link1.
     * @return FkTripsVehiclesAssoc3Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc3Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc4Link1.
     * @return FkTripsVehiclesAssoc4Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc4Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc5Link1.
     * @return FkTripsVehiclesAssoc5Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc5Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc6Link1.
     * @return FkTripsVehiclesAssoc6Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc6Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc7Link1.
     * @return FkTripsVehiclesAssoc7Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc7Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc8Link1.
     * @return FkTripsVehiclesAssoc8Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc8Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc8Link1.
     * @return FkTripsDriversAssoc8Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc8Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc8Link1.
     * @return FkTripsBookingsAssoc8Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc8Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc8Link1.
     * @return FkRefillsVehiclesAssoc8Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc8Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc8Link1.
     * @return FkBookingsUsersAssoc8Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc8Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc8Link1.
     * @return FkBookingsTransportItemsAssoc8Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc8Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc8Link1.
     * @return FkBookingsBookingTypesAssoc8Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc8Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc8Link1.
     * @return FkBookingsBookingStatusAssoc8Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc8Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc9Link1.
     * @return FkTripsVehiclesAssoc9Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc9Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc9Link1.
     * @return FkTripsDriversAssoc9Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc9Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc9Link1.
     * @return FkTripsBookingsAssoc9Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc9Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc9Link1.
     * @return FkRefillsVehiclesAssoc9Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc9Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc9Link1.
     * @return FkBookingsUsersAssoc9Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc9Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc9Link1.
     * @return FkBookingsTransportItemsAssoc9Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc9Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc9Link1.
     * @return FkBookingsBookingTypesAssoc9Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc9Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc9Link1.
     * @return FkBookingsBookingStatusAssoc9Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc9Link1");
    }

    /**
     * Container's getter for FkUsersUnitsLink1.
     * @return FkUsersUnitsLink1
     */
    public ViewLinkImpl getFkUsersUnitsLink1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsLink1");
    }

    /**
     * Container's getter for FkUsersRolesLink1.
     * @return FkUsersRolesLink1
     */
    public ViewLinkImpl getFkUsersRolesLink1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesLink1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc1Link1.
     * @return FkUsersRolesAssoc1Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc1Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc2Link1.
     * @return FkUsersRolesAssoc2Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc2Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc3Link1.
     * @return FkUsersRolesAssoc3Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc3Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc4Link1.
     * @return FkUsersRolesAssoc4Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc4Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc5Link1.
     * @return FkUsersRolesAssoc5Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc5Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc6Link1.
     * @return FkUsersRolesAssoc6Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc6Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc7Link1.
     * @return FkUsersRolesAssoc7Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc7Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc8Link1.
     * @return FkUsersRolesAssoc8Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc8Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc9Link1.
     * @return FkUsersRolesAssoc9Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc9Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc1Link1.
     * @return FkUsersUnitsAssoc1Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc1Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc1Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc2Link1.
     * @return FkUsersUnitsAssoc2Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc2Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc2Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc3Link1.
     * @return FkUsersUnitsAssoc3Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc3Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc3Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc4Link1.
     * @return FkUsersUnitsAssoc4Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc4Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc4Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc5Link1.
     * @return FkUsersUnitsAssoc5Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc5Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc5Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc6Link1.
     * @return FkUsersUnitsAssoc6Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc6Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc6Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc7Link1.
     * @return FkUsersUnitsAssoc7Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc7Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc7Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc8Link1.
     * @return FkUsersUnitsAssoc8Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc8Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc8Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc9Link1.
     * @return FkUsersUnitsAssoc9Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc9Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc9Link1");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc10Link1.
     * @return FkTripsVehiclesAssoc10Link1
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc10Link1");
    }

    /**
     * Container's getter for FkTripsDriversAssoc10Link1.
     * @return FkTripsDriversAssoc10Link1
     */
    public ViewLinkImpl getFkTripsDriversAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc10Link1");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc10Link1.
     * @return FkTripsBookingsAssoc10Link1
     */
    public ViewLinkImpl getFkTripsBookingsAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc10Link1");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc10Link1.
     * @return FkRefillsVehiclesAssoc10Link1
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc10Link1");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc10Link1.
     * @return FkBookingsUsersAssoc10Link1
     */
    public ViewLinkImpl getFkBookingsUsersAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc10Link1");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc10Link1.
     * @return FkBookingsTransportItemsAssoc10Link1
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc10Link1");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc10Link1.
     * @return FkBookingsBookingTypesAssoc10Link1
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc10Link1");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc10Link1.
     * @return FkBookingsBookingStatusAssoc10Link1
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc10Link1");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc10Link1.
     * @return FkUsersUnitsAssoc10Link1
     */
    public ViewLinkImpl getFkUsersUnitsAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc10Link1");
    }

    /**
     * Container's getter for FkUsersRolesAssoc10Link1.
     * @return FkUsersRolesAssoc10Link1
     */
    public ViewLinkImpl getFkUsersRolesAssoc10Link1() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc10Link1");
    }

    /**
     * Container's getter for EmailPropertiesView1.
     * @return EmailPropertiesView1
     */
    public EmailPropertiesViewImpl getEmailPropertiesView1() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView1");
    }

    /**
     * Container's getter for TripsView35.
     * @return TripsView35
     */
    public ViewObjectImpl getTripsView35() {
        return (ViewObjectImpl) findViewObject("TripsView35");
    }

    /**
     * Container's getter for EmailPropertiesView2.
     * @return EmailPropertiesView2
     */
    public EmailPropertiesViewImpl getEmailPropertiesView2() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView2");
    }

    /**
     * Container's getter for TripsView36.
     * @return TripsView36
     */
    public ViewObjectImpl getTripsView36() {
        return (ViewObjectImpl) findViewObject("TripsView36");
    }

    /**
     * Container's getter for EmailPropertiesView3.
     * @return EmailPropertiesView3
     */
    public EmailPropertiesViewImpl getEmailPropertiesView3() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView3");
    }

    /**
     * Container's getter for TripsView37.
     * @return TripsView37
     */
    public ViewObjectImpl getTripsView37() {
        return (ViewObjectImpl) findViewObject("TripsView37");
    }

    /**
     * Container's getter for EmailPropertiesView4.
     * @return EmailPropertiesView4
     */
    public EmailPropertiesViewImpl getEmailPropertiesView4() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView4");
    }

    /**
     * Container's getter for RefillsView13.
     * @return RefillsView13
     */
    public ViewObjectImpl getRefillsView13() {
        return (ViewObjectImpl) findViewObject("RefillsView13");
    }

    /**
     * Container's getter for EmailPropertiesView5.
     * @return EmailPropertiesView5
     */
    public EmailPropertiesViewImpl getEmailPropertiesView5() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView5");
    }

    /**
     * Container's getter for BookingsView46.
     * @return BookingsView46
     */
    public BookingsViewImpl getBookingsView46() {
        return (BookingsViewImpl) findViewObject("BookingsView46");
    }

    /**
     * Container's getter for EmailPropertiesView6.
     * @return EmailPropertiesView6
     */
    public EmailPropertiesViewImpl getEmailPropertiesView6() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView6");
    }

    /**
     * Container's getter for BookingsView47.
     * @return BookingsView47
     */
    public BookingsViewImpl getBookingsView47() {
        return (BookingsViewImpl) findViewObject("BookingsView47");
    }

    /**
     * Container's getter for EmailPropertiesView7.
     * @return EmailPropertiesView7
     */
    public EmailPropertiesViewImpl getEmailPropertiesView7() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView7");
    }

    /**
     * Container's getter for BookingsView48.
     * @return BookingsView48
     */
    public BookingsViewImpl getBookingsView48() {
        return (BookingsViewImpl) findViewObject("BookingsView48");
    }

    /**
     * Container's getter for EmailPropertiesView8.
     * @return EmailPropertiesView8
     */
    public EmailPropertiesViewImpl getEmailPropertiesView8() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView8");
    }

    /**
     * Container's getter for BookingsView49.
     * @return BookingsView49
     */
    public BookingsViewImpl getBookingsView49() {
        return (BookingsViewImpl) findViewObject("BookingsView49");
    }

    /**
     * Container's getter for EmailPropertiesView9.
     * @return EmailPropertiesView9
     */
    public EmailPropertiesViewImpl getEmailPropertiesView9() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView9");
    }

    /**
     * Container's getter for UsersView24.
     * @return UsersView24
     */
    public UsersViewImpl getUsersView24() {
        return (UsersViewImpl) findViewObject("UsersView24");
    }

    /**
     * Container's getter for EmailPropertiesView10.
     * @return EmailPropertiesView10
     */
    public EmailPropertiesViewImpl getEmailPropertiesView10() {
        return (EmailPropertiesViewImpl) findViewObject("EmailPropertiesView10");
    }

    /**
     * Container's getter for UsersView25.
     * @return UsersView25
     */
    public UsersViewImpl getUsersView25() {
        return (UsersViewImpl) findViewObject("UsersView25");
    }

    /**
     * Container's getter for FkTripsVehiclesAssoc11Link.
     * @return FkTripsVehiclesAssoc11Link
     */
    public ViewLinkImpl getFkTripsVehiclesAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkTripsVehiclesAssoc11Link");
    }

    /**
     * Container's getter for FkTripsDriversAssoc11Link.
     * @return FkTripsDriversAssoc11Link
     */
    public ViewLinkImpl getFkTripsDriversAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkTripsDriversAssoc11Link");
    }

    /**
     * Container's getter for FkTripsBookingsAssoc11Link.
     * @return FkTripsBookingsAssoc11Link
     */
    public ViewLinkImpl getFkTripsBookingsAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkTripsBookingsAssoc11Link");
    }

    /**
     * Container's getter for FkRefillsVehiclesAssoc11Link.
     * @return FkRefillsVehiclesAssoc11Link
     */
    public ViewLinkImpl getFkRefillsVehiclesAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkRefillsVehiclesAssoc11Link");
    }

    /**
     * Container's getter for FkBookingsUsersAssoc11Link.
     * @return FkBookingsUsersAssoc11Link
     */
    public ViewLinkImpl getFkBookingsUsersAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkBookingsUsersAssoc11Link");
    }

    /**
     * Container's getter for FkBookingsTransportItemsAssoc11Link.
     * @return FkBookingsTransportItemsAssoc11Link
     */
    public ViewLinkImpl getFkBookingsTransportItemsAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkBookingsTransportItemsAssoc11Link");
    }

    /**
     * Container's getter for FkBookingsBookingTypesAssoc11Link.
     * @return FkBookingsBookingTypesAssoc11Link
     */
    public ViewLinkImpl getFkBookingsBookingTypesAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingTypesAssoc11Link");
    }

    /**
     * Container's getter for FkBookingsBookingStatusAssoc11Link.
     * @return FkBookingsBookingStatusAssoc11Link
     */
    public ViewLinkImpl getFkBookingsBookingStatusAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkBookingsBookingStatusAssoc11Link");
    }

    /**
     * Container's getter for FkUsersUnitsAssoc11Link.
     * @return FkUsersUnitsAssoc11Link
     */
    public ViewLinkImpl getFkUsersUnitsAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkUsersUnitsAssoc11Link");
    }

    /**
     * Container's getter for FkUsersRolesAssoc11Link.
     * @return FkUsersRolesAssoc11Link
     */
    public ViewLinkImpl getFkUsersRolesAssoc11Link() {
        return (ViewLinkImpl) findViewLink("FkUsersRolesAssoc11Link");
    }

    /**
     * Container's getter for BookingsPendingView1.
     * @return BookingsPendingView1
     */
    public BookingsPendingViewImpl getBookingsPendingView1() {
        return (BookingsPendingViewImpl) findViewObject("BookingsPendingView1");
    }

    /**
     * Container's getter for BookingsUnProcessed1.
     * @return BookingsUnProcessed1
     */
    public BookingsUnProcessedImpl getBookingsUnProcessed1() {
        return (BookingsUnProcessedImpl) findViewObject("BookingsUnProcessed1");
    }

    /**
     * Container's getter for BookingsPending1.
     * @return BookingsPending1
     */
    public BookingsViewImpl getBookingsPending1() {
        return (BookingsViewImpl) findViewObject("BookingsPending1");
    }

    /**
     * Container's getter for LoginUsersView1.
     * @return LoginUsersView1
     */
    public LoginUsersViewImpl getLoginUsersView1() {
        return (LoginUsersViewImpl) findViewObject("LoginUsersView1");
    }

    /**
     * Container's getter for TripPassengersView1.
     * @return TripPassengersView1
     */
    public TripPassengersViewImpl getTripPassengersView1() {
        return (TripPassengersViewImpl) findViewObject("TripPassengersView1");
    }
    
    public boolean joinTrip(int bookingId){
        boolean joinStatus = false;
        ApplicationModule appMod=null;
        TripPassengersViewImpl vo;           
        int userId = 0;
        try{
            appMod = Configuration.createRootApplicationModule("fleet.model.AppModuleFleet","AppModuleFleetLocal");
            vo = (TripPassengersViewImpl)appMod.findViewObject("TripPassengersView1");          
            userId = UsersViewImpl.getLoggedinUserId();
            Row row = vo.createRow();
            row.setAttribute("BookingId", bookingId);
            row.setAttribute("UserId", userId);
            vo.executeQuery();
            vo.getDBTransaction().commit();
            joinStatus = true;        
        }catch(Exception exception){
            System.err.println("Error joining trip in joinTrip()");
            joinStatus = false;
          //  exception.printStackTrace();
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }            
            vo = null;
        }
        return joinStatus;
    }  
    
    public boolean leaveTrip(int bookingId, int userId){
        boolean success = false;
        ApplicationModule appMod=null;
        TripPassengersViewImpl vo;           
       // int userId = 0;
        try{
            appMod = Configuration.createRootApplicationModule("fleet.model.AppModuleFleet","AppModuleFleetLocal");
            vo = (TripPassengersViewImpl)appMod.findViewObject("TripPassengersView1");          
            userId = UsersViewImpl.getLoggedinUserId();
            ViewCriteria viewCriteria = vo.createViewCriteria();
            ViewCriteriaRow viewCriteriaRow = viewCriteria.createViewCriteriaRow();
            viewCriteriaRow.setAttribute("BookingId", bookingId);
            viewCriteriaRow.setAttribute("UserId", userId);
            viewCriteria.add(viewCriteriaRow);
            viewCriteria.setCriteriaMode(ViewCriteria.CRITERIA_MODE_CACHE);
            vo.applyViewCriteria(viewCriteria);
            vo.executeQuery();
            while(vo.hasNext()){
                TripPassengersViewRowImpl row = (TripPassengersViewRowImpl)vo.next();
                row.setAttribute("OnTrip", 0);
            }          
            vo.getDBTransaction().commit();
            vo.executeQuery();
            success = true;        
        }catch(Exception exception){
            System.err.println("Error leaving trip in leaveTrip() method");
            success = false;
           // exception.printStackTrace();
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }            
            vo = null;
        }
        return success;
    }       
    
    //Create booking
  /*  public boolean createBooking(int userId, int bookingForUserId, int bookingTypeId, int itemsTransportedId, java.util.Date expectedTravelTime, java.util.Date tripEndTime, String destination, String bookingStaffComments){
        boolean bookingCreated = false;
        ApplicationModule appMod;
        BookingsViewImpl vo;          
        try{
            appMod = Configuration.createRootApplicationModule("fleet.model.AppModuleFleet","AppModuleFleetShared");
            vo = (BookingsViewImpl)appMod.findViewObject("BookingsView1");   
            Row row = vo.createRow();
            row.setAttribute("UserId", userId);
            row.setAttribute("BookingForUserId", bookingForUserId);
            row.setAttribute("BookingTypeId", bookingTypeId);
            row.setAttribute("ExpectedTravelTime", expectedTravelTime);
            row.setAttribute("TripEndTime", tripEndTime);
            row.setAttribute("Destination", destination);
            row.setAttribute("ItemsTransportedId", itemsTransportedId);
            row.setAttribute("BookingStaffComments", bookingStaffComments);
            appMod.getTransaction().commit();
            vo.executeQuery();
            bookingCreated = true;
            row.getAttributeValues();
            System.err.println("Finished");
        }catch(Exception exception){
            System.err.println("Error creating booking in createBooking() method");
            bookingCreated = false;
        }finally{
            appMod = null;
            vo = null;
        }
        return bookingCreated;
    } */
    
  public boolean insertTripPassenger(int bookingId, int userId){
      boolean success = false;
      ApplicationModule appMod=null;
      TripPassengersViewImpl vo;
      try{
          appMod = Configuration.createRootApplicationModule("fleet.model.AppModuleFleet", "AppModuleFleetLocal");          
          vo = (TripPassengersViewImpl)appMod.findViewObject("TripPassengersView1");          
          Row row = vo.createRow();
          row.setAttribute("BookingId", bookingId);
          row.setAttribute("UserId", userId);
          vo.insertRow(row);
          //this.getDBTransaction().commit();
          vo.getDBTransaction().commit();
          vo.executeQuery();
          success = true;
      }catch(Exception exception){
          success = false;
          System.err.println("Error inserting trip passenger in insertTripPassenger method");
          exception.printStackTrace();
      }finally{
          if(appMod != null){
              Configuration.releaseRootApplicationModule(appMod, false);                      
          }          
      }
      return success;
  }
  
    public boolean isUserOnTrip(int bookingId){
        boolean isUserOnTrip = false;
        ApplicationModule appMod=null;
        TripPassengersViewImpl vo;
        UsersViewImpl usersViewImpl;// = new UsersViewImpl();
        TripPassengersViewRowImpl row;
        int loggedInUser = 0;
        int userId = 0;
        int onTripFlag = 0;
        try{
            appMod = Configuration.createRootApplicationModule("fleet.model.AppModuleFleet","AppModuleFleetLocal");
            vo = (TripPassengersViewImpl)appMod.findViewObject("TripPassengersView1");     
            ViewCriteria viewCriteria = vo.createViewCriteria();
            ViewCriteriaRow viewCriteriaRow = viewCriteria.createViewCriteriaRow();
            viewCriteriaRow.setAttribute("BookingId", bookingId);
            viewCriteria.add(viewCriteriaRow);
            viewCriteria.setCriteriaMode(ViewCriteria.CRITERIA_MODE_CACHE);
            vo.applyViewCriteria(viewCriteria);
            vo.executeQuery();
            usersViewImpl = new UsersViewImpl();
            while(vo.hasNext()){
                row = (TripPassengersViewRowImpl)vo.next();
                userId = row.getAttribute("UserId") != null ? Integer.parseInt(row.getAttribute("UserId").toString()) : 0;
                //userId = UsersViewImpl.getLoggedinUserId();
                onTripFlag = row.getAttribute("OnTrip") != null ? Integer.parseInt(row.getAttribute("OnTrip").toString()) : 0;
                //loggedInUser = UsersViewImpl.getCurrentlyLoggedInUserId();
                loggedInUser = UsersViewImpl.loggedinUserId;
                if(userId == loggedInUser && onTripFlag == 1) {
                    isUserOnTrip = true;
                }
            }
        }catch(Exception exception){
            System.err.println("Error finding if user is on trip");
            exception.printStackTrace();
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }           
            vo = null;
            usersViewImpl = null;
        }
        return isUserOnTrip;
    }

    /**
     * Container's getter for DriverStatusView1.
     * @return DriverStatusView1
     */
    public ViewObjectImpl getDriverStatusView1() {
        return (ViewObjectImpl) findViewObject("DriverStatusView1");
    }

    /**
     * Container's getter for VehicleStatusView1.
     * @return VehicleStatusView1
     */
    public ViewObjectImpl getVehicleStatusView1() {
        return (ViewObjectImpl) findViewObject("VehicleStatusView1");
    }

    /**
     * Container's getter for ProcessBookingsView1.
     * @return ProcessBookingsView1
     */
    public BookingsViewImpl getProcessBookingsView1() {
        return (BookingsViewImpl) findViewObject("ProcessBookingsView1");
    }

    /**
     * Container's getter for AvailableDriversView1.
     * @return AvailableDriversView1
     */
    public AvailableDriversViewImpl getAvailableDriversView1() {
        return (AvailableDriversViewImpl) findViewObject("AvailableDriversView1");
    }

    /**
     * Container's getter for AvailableVehicles1.
     * @return AvailableVehicles1
     */
    public AvailableVehiclesImpl getAvailableVehicles1() {
        return (AvailableVehiclesImpl) findViewObject("AvailableVehicles1");
    }

    /**
     * Container's getter for UnprocessedBookings1.
     * @return UnprocessedBookings1
     */
    public UnprocessedBookingsImpl getUnprocessedBookings1() {
        return (UnprocessedBookingsImpl) findViewObject("UnprocessedBookings1");
    }
}

