package fleet.model;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 06 12:27:50 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AvailableDriversViewRowImpl extends ViewRowImpl {

    public static final int MAXUSAGECONST = 1;

    /**
     * This is the default constructor (do not remove).
     */
    public AvailableDriversViewRowImpl() {
    }
}

