package fleet.model;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 19 13:26:38 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookingsViewRowImpl extends ViewRowImpl implements fleet.model.common.BookingsViewRow {


    public static final int ENTITY_BOOKINGS = 0;
    public static final int ENTITY_VEHICLES = 1;
    public static final int ENTITY_DRIVERS = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        UserId,
        BookingTypeId,
        BookingTime,
        ExpectedTravelTime,
        Destination,
        BookingForUserId,
        ItemsTransportedId,
        BookingStaffComments,
        BookingActionTime,
        ApprovingStaffComments,
        BookingStatusId,
        IsActive,
        TripEndTime,
        ProviderId,
        IdString,
        Recurring,
        TimeType,
        AllDay,
        Timezone,
        AllocatedDriverId,
        AllocatedVehicleId,
        DriversTransient,
        VehiclesTransient,
        Registration,
        Id1,
        FirstName,
        LastName,
        OtherNames,
        Id2,
        BookingsView,
        BookingsView1,
        BookingsView2,
        BookingsView3,
        RefillsView,
        TripsView,
        TripsView1,
        TripsView2,
        UsersView,
        UsersView1,
        UsersView2,
        BookingTypesView1,
        TransportItemsView1,
        BookingStatusView1,
        VehiclesView1,
        DriversView1,
        DriverStatusView1,
        DriversView2,
        VehiclesView2,
        AvailableDriversView1,
        AvailableVehicles1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int BOOKINGTYPEID = AttributesEnum.BookingTypeId.index();
    public static final int BOOKINGTIME = AttributesEnum.BookingTime.index();
    public static final int EXPECTEDTRAVELTIME = AttributesEnum.ExpectedTravelTime.index();
    public static final int DESTINATION = AttributesEnum.Destination.index();
    public static final int BOOKINGFORUSERID = AttributesEnum.BookingForUserId.index();
    public static final int ITEMSTRANSPORTEDID = AttributesEnum.ItemsTransportedId.index();
    public static final int BOOKINGSTAFFCOMMENTS = AttributesEnum.BookingStaffComments.index();
    public static final int BOOKINGACTIONTIME = AttributesEnum.BookingActionTime.index();
    public static final int APPROVINGSTAFFCOMMENTS = AttributesEnum.ApprovingStaffComments.index();
    public static final int BOOKINGSTATUSID = AttributesEnum.BookingStatusId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int TRIPENDTIME = AttributesEnum.TripEndTime.index();
    public static final int PROVIDERID = AttributesEnum.ProviderId.index();
    public static final int IDSTRING = AttributesEnum.IdString.index();
    public static final int RECURRING = AttributesEnum.Recurring.index();
    public static final int TIMETYPE = AttributesEnum.TimeType.index();
    public static final int ALLDAY = AttributesEnum.AllDay.index();
    public static final int TIMEZONE = AttributesEnum.Timezone.index();
    public static final int ALLOCATEDDRIVERID = AttributesEnum.AllocatedDriverId.index();
    public static final int ALLOCATEDVEHICLEID = AttributesEnum.AllocatedVehicleId.index();
    public static final int DRIVERSTRANSIENT = AttributesEnum.DriversTransient.index();
    public static final int VEHICLESTRANSIENT = AttributesEnum.VehiclesTransient.index();
    public static final int REGISTRATION = AttributesEnum.Registration.index();
    public static final int ID1 = AttributesEnum.Id1.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int OTHERNAMES = AttributesEnum.OtherNames.index();
    public static final int ID2 = AttributesEnum.Id2.index();
    public static final int BOOKINGSVIEW = AttributesEnum.BookingsView.index();
    public static final int BOOKINGSVIEW1 = AttributesEnum.BookingsView1.index();
    public static final int BOOKINGSVIEW2 = AttributesEnum.BookingsView2.index();
    public static final int BOOKINGSVIEW3 = AttributesEnum.BookingsView3.index();
    public static final int REFILLSVIEW = AttributesEnum.RefillsView.index();
    public static final int TRIPSVIEW = AttributesEnum.TripsView.index();
    public static final int TRIPSVIEW1 = AttributesEnum.TripsView1.index();
    public static final int TRIPSVIEW2 = AttributesEnum.TripsView2.index();
    public static final int USERSVIEW = AttributesEnum.UsersView.index();
    public static final int USERSVIEW1 = AttributesEnum.UsersView1.index();
    public static final int USERSVIEW2 = AttributesEnum.UsersView2.index();
    public static final int BOOKINGTYPESVIEW1 = AttributesEnum.BookingTypesView1.index();
    public static final int TRANSPORTITEMSVIEW1 = AttributesEnum.TransportItemsView1.index();
    public static final int BOOKINGSTATUSVIEW1 = AttributesEnum.BookingStatusView1.index();
    public static final int VEHICLESVIEW1 = AttributesEnum.VehiclesView1.index();
    public static final int DRIVERSVIEW1 = AttributesEnum.DriversView1.index();
    public static final int DRIVERSTATUSVIEW1 = AttributesEnum.DriverStatusView1.index();
    public static final int DRIVERSVIEW2 = AttributesEnum.DriversView2.index();
    public static final int VEHICLESVIEW2 = AttributesEnum.VehiclesView2.index();
    public static final int AVAILABLEDRIVERSVIEW1 = AttributesEnum.AvailableDriversView1.index();
    public static final int AVAILABLEVEHICLES1 = AttributesEnum.AvailableVehicles1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BookingsViewRowImpl() {
    }

    /**
     * Gets Bookings entity object.
     * @return the Bookings
     */
    public BookingsImpl getBookings() {
        return (BookingsImpl) getEntity(ENTITY_BOOKINGS);
    }

    /**
     * Gets Vehicles entity object.
     * @return the Vehicles
     */
    public EntityImpl getVehicles() {
        return (EntityImpl) getEntity(ENTITY_VEHICLES);
    }

    /**
     * Gets Drivers entity object.
     * @return the Drivers
     */
    public EntityImpl getDrivers() {
        return (EntityImpl) getEntity(ENTITY_DRIVERS);
    }

    /**
     * Gets the attribute value for id using the alias name Id.
     * @return the id
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name Id.
     * @param value value to set the id
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for user_id using the alias name UserId.
     * @return the user_id
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for user_id using the alias name UserId.
     * @param value value to set the user_id
     */
    public void setUserId(Integer value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for booking_type_id using the alias name BookingTypeId.
     * @return the booking_type_id
     */
    public Integer getBookingTypeId() {
        return (Integer) getAttributeInternal(BOOKINGTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for booking_type_id using the alias name BookingTypeId.
     * @param value value to set the booking_type_id
     */
    public void setBookingTypeId(Integer value) {
        setAttributeInternal(BOOKINGTYPEID, value);
    }

    /**
     * Gets the attribute value for booking_time using the alias name BookingTime.
     * @return the booking_time
     */
    public Timestamp getBookingTime() {
        return (Timestamp) getAttributeInternal(BOOKINGTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for booking_time using the alias name BookingTime.
     * @param value value to set the booking_time
     */
    public void setBookingTime(Timestamp value) {
        setAttributeInternal(BOOKINGTIME, value);
    }

    /**
     * Gets the attribute value for expected_travel_time using the alias name ExpectedTravelTime.
     * @return the expected_travel_time
     */
    public Timestamp getExpectedTravelTime() {
        return (Timestamp) getAttributeInternal(EXPECTEDTRAVELTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for expected_travel_time using the alias name ExpectedTravelTime.
     * @param value value to set the expected_travel_time
     */
    public void setExpectedTravelTime(Timestamp value) {
        setAttributeInternal(EXPECTEDTRAVELTIME, value);
    }

    /**
     * Gets the attribute value for destination using the alias name Destination.
     * @return the destination
     */
    public String getDestination() {
        return (String) getAttributeInternal(DESTINATION);
    }

    /**
     * Sets <code>value</code> as attribute value for destination using the alias name Destination.
     * @param value value to set the destination
     */
    public void setDestination(String value) {
        setAttributeInternal(DESTINATION, value);
    }

    /**
     * Gets the attribute value for booking_for_user_id using the alias name BookingForUserId.
     * @return the booking_for_user_id
     */
    public Integer getBookingForUserId() {
        return (Integer) getAttributeInternal(BOOKINGFORUSERID);
    }

    /**
     * Sets <code>value</code> as attribute value for booking_for_user_id using the alias name BookingForUserId.
     * @param value value to set the booking_for_user_id
     */
    public void setBookingForUserId(Integer value) {
        setAttributeInternal(BOOKINGFORUSERID, value);
    }

    /**
     * Gets the attribute value for items_transported_id using the alias name ItemsTransportedId.
     * @return the items_transported_id
     */
    public Integer getItemsTransportedId() {
        return (Integer) getAttributeInternal(ITEMSTRANSPORTEDID);
    }

    /**
     * Sets <code>value</code> as attribute value for items_transported_id using the alias name ItemsTransportedId.
     * @param value value to set the items_transported_id
     */
    public void setItemsTransportedId(Integer value) {
        setAttributeInternal(ITEMSTRANSPORTEDID, value);
    }

    /**
     * Gets the attribute value for booking_staff_comments using the alias name BookingStaffComments.
     * @return the booking_staff_comments
     */
    public String getBookingStaffComments() {
        return (String) getAttributeInternal(BOOKINGSTAFFCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for booking_staff_comments using the alias name BookingStaffComments.
     * @param value value to set the booking_staff_comments
     */
    public void setBookingStaffComments(String value) {
        setAttributeInternal(BOOKINGSTAFFCOMMENTS, value);
    }

    /**
     * Gets the attribute value for booking_action_time using the alias name BookingActionTime.
     * @return the booking_action_time
     */
    public Timestamp getBookingActionTime() {
        return (Timestamp) getAttributeInternal(BOOKINGACTIONTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for booking_action_time using the alias name BookingActionTime.
     * @param value value to set the booking_action_time
     */
    public void setBookingActionTime(Timestamp value) {
        setAttributeInternal(BOOKINGACTIONTIME, value);
    }

    /**
     * Gets the attribute value for approving_staff_comments using the alias name ApprovingStaffComments.
     * @return the approving_staff_comments
     */
    public String getApprovingStaffComments() {
        return (String) getAttributeInternal(APPROVINGSTAFFCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for approving_staff_comments using the alias name ApprovingStaffComments.
     * @param value value to set the approving_staff_comments
     */
    public void setApprovingStaffComments(String value) {
        setAttributeInternal(APPROVINGSTAFFCOMMENTS, value);
    }

    /**
     * Gets the attribute value for booking_status_id using the alias name BookingStatusId.
     * @return the booking_status_id
     */
    public Integer getBookingStatusId() {
        return (Integer) getAttributeInternal(BOOKINGSTATUSID);
    }

    /**
     * Sets <code>value</code> as attribute value for booking_status_id using the alias name BookingStatusId.
     * @param value value to set the booking_status_id
     */
    public void setBookingStatusId(Integer value) {
        setAttributeInternal(BOOKINGSTATUSID, value);
    }

    /**
     * Gets the attribute value for is_active using the alias name IsActive.
     * @return the is_active
     */
    public Integer getIsActive() {
        return (Integer) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for is_active using the alias name IsActive.
     * @param value value to set the is_active
     */
    public void setIsActive(Integer value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for trip_end_time using the alias name TripEndTime.
     * @return the trip_end_time
     */
    public Timestamp getTripEndTime() {
        return (Timestamp) getAttributeInternal(TRIPENDTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for trip_end_time using the alias name TripEndTime.
     * @param value value to set the trip_end_time
     */
    public void setTripEndTime(Timestamp value) {
        setAttributeInternal(TRIPENDTIME, value);
    }

    /**
     * Gets the attribute value for provider_id using the alias name ProviderId.
     * @return the provider_id
     */
    public String getProviderId() {
        return (String) getAttributeInternal(PROVIDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for provider_id using the alias name ProviderId.
     * @param value value to set the provider_id
     */
    public void setProviderId(String value) {
        setAttributeInternal(PROVIDERID, value);
    }

    /**
     * Gets the attribute value for id_string using the alias name IdString.
     * @return the id_string
     */
    public String getIdString() {
        return (String) getAttributeInternal(IDSTRING);
    }

    /**
     * Sets <code>value</code> as attribute value for id_string using the alias name IdString.
     * @param value value to set the id_string
     */
    public void setIdString(String value) {
        setAttributeInternal(IDSTRING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Recurring.
     * @return the Recurring
     */
    public String getRecurring() {
        return (String) getAttributeInternal(RECURRING);
    }

    /**
     * Gets the attribute value for the calculated attribute TimeType.
     * @return the TimeType
     */
    public String getTimeType() {
        return (String) getAttributeInternal(TIMETYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute AllDay.
     * @return the AllDay
     */
    public String getAllDay() {
        return (String) getAttributeInternal(ALLDAY);
    }

    /**
     * Gets the attribute value for the calculated attribute Timezone.
     * @return the Timezone
     */
    public String getTimezone() {
        return (String) getAttributeInternal(TIMEZONE);
    }

    /**
     * Gets the attribute value for allocated_driver_id using the alias name AllocatedDriverId.
     * @return the allocated_driver_id
     */
    public Integer getAllocatedDriverId() {
        return (Integer) getAttributeInternal(ALLOCATEDDRIVERID);
    }

    /**
     * Sets <code>value</code> as attribute value for allocated_driver_id using the alias name AllocatedDriverId.
     * @param value value to set the allocated_driver_id
     */
    public void setAllocatedDriverId(Integer value) {
        setAttributeInternal(ALLOCATEDDRIVERID, value);
    }

    /**
     * Gets the attribute value for allocated_vehicle_id using the alias name AllocatedVehicleId.
     * @return the allocated_vehicle_id
     */
    public Integer getAllocatedVehicleId() {
        return (Integer) getAttributeInternal(ALLOCATEDVEHICLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for allocated_vehicle_id using the alias name AllocatedVehicleId.
     * @param value value to set the allocated_vehicle_id
     */
    public void setAllocatedVehicleId(Integer value) {
        setAttributeInternal(ALLOCATEDVEHICLEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DriversTransient.
     * @return the DriversTransient
     */
    public String getDriversTransient() {
        return (String) getAttributeInternal(DRIVERSTRANSIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DriversTransient.
     * @param value value to set the  DriversTransient
     */
    public void setDriversTransient(String value) {
        setAttributeInternal(DRIVERSTRANSIENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VehiclesTransient.
     * @return the VehiclesTransient
     */
    public String getVehiclesTransient() {
        return (String) getAttributeInternal(VEHICLESTRANSIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VehiclesTransient.
     * @param value value to set the  VehiclesTransient
     */
    public void setVehiclesTransient(String value) {
        setAttributeInternal(VEHICLESTRANSIENT, value);
    }

    /**
     * Gets the attribute value for registration using the alias name Registration.
     * @return the registration
     */
    public String getRegistration() {
        return (String) getAttributeInternal(REGISTRATION);
    }

    /**
     * Sets <code>value</code> as attribute value for registration using the alias name Registration.
     * @param value value to set the registration
     */
    public void setRegistration(String value) {
        setAttributeInternal(REGISTRATION, value);
    }

    /**
     * Gets the attribute value for id using the alias name Id1.
     * @return the id
     */
    public Integer getId1() {
        return (Integer) getAttributeInternal(ID1);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name Id1.
     * @param value value to set the id
     */
    public void setId1(Integer value) {
        setAttributeInternal(ID1, value);
    }

    /**
     * Gets the attribute value for first_name using the alias name FirstName.
     * @return the first_name
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for first_name using the alias name FirstName.
     * @param value value to set the first_name
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for last_name using the alias name LastName.
     * @return the last_name
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for last_name using the alias name LastName.
     * @param value value to set the last_name
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for other_names using the alias name OtherNames.
     * @return the other_names
     */
    public String getOtherNames() {
        return (String) getAttributeInternal(OTHERNAMES);
    }

    /**
     * Sets <code>value</code> as attribute value for other_names using the alias name OtherNames.
     * @param value value to set the other_names
     */
    public void setOtherNames(String value) {
        setAttributeInternal(OTHERNAMES, value);
    }

    /**
     * Gets the attribute value for id using the alias name Id2.
     * @return the id
     */
    public Integer getId2() {
        return (Integer) getAttributeInternal(ID2);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name Id2.
     * @param value value to set the id
     */
    public void setId2(Integer value) {
        setAttributeInternal(ID2, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView.
     */
    public RowIterator getBookingsView() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView1.
     */
    public RowIterator getBookingsView1() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView2.
     */
    public RowIterator getBookingsView2() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW2);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView3.
     */
    public RowIterator getBookingsView3() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW3);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RefillsView.
     */
    public RowIterator getRefillsView() {
        return (RowIterator) getAttributeInternal(REFILLSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView.
     */
    public RowIterator getTripsView() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView1.
     */
    public RowIterator getTripsView1() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView2.
     */
    public RowIterator getTripsView2() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW2);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UsersView.
     */
    public RowIterator getUsersView() {
        return (RowIterator) getAttributeInternal(USERSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UsersView1.
     */
    public RowIterator getUsersView1() {
        return (RowIterator) getAttributeInternal(USERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UsersView2.
     */
    public RowSet getUsersView2() {
        return (RowSet) getAttributeInternal(USERSVIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BookingTypesView1.
     */
    public RowSet getBookingTypesView1() {
        return (RowSet) getAttributeInternal(BOOKINGTYPESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TransportItemsView1.
     */
    public RowSet getTransportItemsView1() {
        return (RowSet) getAttributeInternal(TRANSPORTITEMSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BookingStatusView1.
     */
    public RowSet getBookingStatusView1() {
        return (RowSet) getAttributeInternal(BOOKINGSTATUSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VehiclesView1.
     */
    public RowSet getVehiclesView1() {
        return (RowSet) getAttributeInternal(VEHICLESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DriversView1.
     */
    public RowSet getDriversView1() {
        return (RowSet) getAttributeInternal(DRIVERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DriverStatusView1.
     */
    public RowSet getDriverStatusView1() {
        return (RowSet) getAttributeInternal(DRIVERSTATUSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DriversView2.
     */
    public RowSet getDriversView2() {
        return (RowSet) getAttributeInternal(DRIVERSVIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VehiclesView2.
     */
    public RowSet getVehiclesView2() {
        return (RowSet) getAttributeInternal(VEHICLESVIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AvailableDriversView1.
     */
    public RowSet getAvailableDriversView1() {
        return (RowSet) getAttributeInternal(AVAILABLEDRIVERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AvailableVehicles1.
     */
    public RowSet getAvailableVehicles1() {
        return (RowSet) getAttributeInternal(AVAILABLEVEHICLES1);
    }
}

