package fleet.model;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 15 08:14:49 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookingsUnProcessedRowImpl extends BookingsViewRowImpl {


    public static final int MAXUSAGECONST = 1;

    /**
     * This is the default constructor (do not remove).
     */
    public BookingsUnProcessedRowImpl() {
    }
}

