package fleet.model;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

import fleet.*;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 19 12:50:05 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookingsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        UserId,
        BookingTypeId,
        BookingTime,
        ExpectedTravelTime,
        Destination,
        BookingForUserId,
        ItemsTransportedId,
        BookingStaffComments,
        BookingActionTime,
        ApprovingStaffComments,
        BookingStatusId,
        IsActive,
        IdString,
        ProviderId,
        TripEndTime,
        AllocatedDriverId,
        AllocatedVehicleId,
        Bookings,
        UserIdBookings,
        Bookings1,
        ItemsTransportedIdBookings,
        Bookings2,
        BookingTypeIdBookings,
        Bookings3,
        BookingStatusIdBookings,
        BookingStatus,
        BookingTypes,
        BookingStatus1,
        BookingTypes1,
        BookingStatus2,
        BookingTypes2,
        BookingStatus3,
        BookingTypes3,
        Drivers,
        Drivers1,
        Drivers2,
        Drivers3,
        Refills,
        Refills1,
        Refills2,
        Refills3,
        Refills4,
        Roles,
        Roles1,
        Roles2,
        Roles3,
        TransportItems,
        TransportItems1,
        TransportItems2,
        TransportItems3,
        Trips,
        Trips1,
        Trips2,
        Trips3,
        Trips4,
        Trips5,
        Trips6,
        Units,
        Units1,
        Units2,
        Units3,
        Users,
        Users1,
        Users2,
        Users3,
        Users4,
        Users5,
        Vehicles,
        Vehicles1,
        Vehicles2,
        Vehicles3,
        EmailProperties,
        EmailProperties1,
        EmailProperties2,
        EmailProperties3;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    private UsersViewImpl usersViewImpl;
    private EmailPropertiesViewImpl emailPropertiesViewImpl;


    public static final int ID = AttributesEnum.Id.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int BOOKINGTYPEID = AttributesEnum.BookingTypeId.index();
    public static final int BOOKINGTIME = AttributesEnum.BookingTime.index();
    public static final int EXPECTEDTRAVELTIME = AttributesEnum.ExpectedTravelTime.index();
    public static final int DESTINATION = AttributesEnum.Destination.index();
    public static final int BOOKINGFORUSERID = AttributesEnum.BookingForUserId.index();
    public static final int ITEMSTRANSPORTEDID = AttributesEnum.ItemsTransportedId.index();
    public static final int BOOKINGSTAFFCOMMENTS = AttributesEnum.BookingStaffComments.index();
    public static final int BOOKINGACTIONTIME = AttributesEnum.BookingActionTime.index();
    public static final int APPROVINGSTAFFCOMMENTS = AttributesEnum.ApprovingStaffComments.index();
    public static final int BOOKINGSTATUSID = AttributesEnum.BookingStatusId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int IDSTRING = AttributesEnum.IdString.index();
    public static final int PROVIDERID = AttributesEnum.ProviderId.index();
    public static final int TRIPENDTIME = AttributesEnum.TripEndTime.index();
    public static final int ALLOCATEDDRIVERID = AttributesEnum.AllocatedDriverId.index();
    public static final int ALLOCATEDVEHICLEID = AttributesEnum.AllocatedVehicleId.index();
    public static final int BOOKINGS = AttributesEnum.Bookings.index();
    public static final int USERIDBOOKINGS = AttributesEnum.UserIdBookings.index();
    public static final int BOOKINGS1 = AttributesEnum.Bookings1.index();
    public static final int ITEMSTRANSPORTEDIDBOOKINGS = AttributesEnum.ItemsTransportedIdBookings.index();
    public static final int BOOKINGS2 = AttributesEnum.Bookings2.index();
    public static final int BOOKINGTYPEIDBOOKINGS = AttributesEnum.BookingTypeIdBookings.index();
    public static final int BOOKINGS3 = AttributesEnum.Bookings3.index();
    public static final int BOOKINGSTATUSIDBOOKINGS = AttributesEnum.BookingStatusIdBookings.index();
    public static final int BOOKINGSTATUS = AttributesEnum.BookingStatus.index();
    public static final int BOOKINGTYPES = AttributesEnum.BookingTypes.index();
    public static final int BOOKINGSTATUS1 = AttributesEnum.BookingStatus1.index();
    public static final int BOOKINGTYPES1 = AttributesEnum.BookingTypes1.index();
    public static final int BOOKINGSTATUS2 = AttributesEnum.BookingStatus2.index();
    public static final int BOOKINGTYPES2 = AttributesEnum.BookingTypes2.index();
    public static final int BOOKINGSTATUS3 = AttributesEnum.BookingStatus3.index();
    public static final int BOOKINGTYPES3 = AttributesEnum.BookingTypes3.index();
    public static final int DRIVERS = AttributesEnum.Drivers.index();
    public static final int DRIVERS1 = AttributesEnum.Drivers1.index();
    public static final int DRIVERS2 = AttributesEnum.Drivers2.index();
    public static final int DRIVERS3 = AttributesEnum.Drivers3.index();
    public static final int REFILLS = AttributesEnum.Refills.index();
    public static final int REFILLS1 = AttributesEnum.Refills1.index();
    public static final int REFILLS2 = AttributesEnum.Refills2.index();
    public static final int REFILLS3 = AttributesEnum.Refills3.index();
    public static final int REFILLS4 = AttributesEnum.Refills4.index();
    public static final int ROLES = AttributesEnum.Roles.index();
    public static final int ROLES1 = AttributesEnum.Roles1.index();
    public static final int ROLES2 = AttributesEnum.Roles2.index();
    public static final int ROLES3 = AttributesEnum.Roles3.index();
    public static final int TRANSPORTITEMS = AttributesEnum.TransportItems.index();
    public static final int TRANSPORTITEMS1 = AttributesEnum.TransportItems1.index();
    public static final int TRANSPORTITEMS2 = AttributesEnum.TransportItems2.index();
    public static final int TRANSPORTITEMS3 = AttributesEnum.TransportItems3.index();
    public static final int TRIPS = AttributesEnum.Trips.index();
    public static final int TRIPS1 = AttributesEnum.Trips1.index();
    public static final int TRIPS2 = AttributesEnum.Trips2.index();
    public static final int TRIPS3 = AttributesEnum.Trips3.index();
    public static final int TRIPS4 = AttributesEnum.Trips4.index();
    public static final int TRIPS5 = AttributesEnum.Trips5.index();
    public static final int TRIPS6 = AttributesEnum.Trips6.index();
    public static final int UNITS = AttributesEnum.Units.index();
    public static final int UNITS1 = AttributesEnum.Units1.index();
    public static final int UNITS2 = AttributesEnum.Units2.index();
    public static final int UNITS3 = AttributesEnum.Units3.index();
    public static final int USERS = AttributesEnum.Users.index();
    public static final int USERS1 = AttributesEnum.Users1.index();
    public static final int USERS2 = AttributesEnum.Users2.index();
    public static final int USERS3 = AttributesEnum.Users3.index();
    public static final int USERS4 = AttributesEnum.Users4.index();
    public static final int USERS5 = AttributesEnum.Users5.index();
    public static final int VEHICLES = AttributesEnum.Vehicles.index();
    public static final int VEHICLES1 = AttributesEnum.Vehicles1.index();
    public static final int VEHICLES2 = AttributesEnum.Vehicles2.index();
    public static final int VEHICLES3 = AttributesEnum.Vehicles3.index();
    public static final int EMAILPROPERTIES = AttributesEnum.EmailProperties.index();
    public static final int EMAILPROPERTIES1 = AttributesEnum.EmailProperties1.index();
    public static final int EMAILPROPERTIES2 = AttributesEnum.EmailProperties2.index();
    public static final int EMAILPROPERTIES3 = AttributesEnum.EmailProperties3.index();
    public static boolean runDoDML = false;

    /**
     * This is the default constructor (do not remove).
     */
    public BookingsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("fleet.model.Bookings");
    }


    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(Integer value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for BookingTypeId, using the alias name BookingTypeId.
     * @return the value of BookingTypeId
     */
    public Integer getBookingTypeId() {
        return (Integer) getAttributeInternal(BOOKINGTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingTypeId.
     * @param value value to set the BookingTypeId
     */
    public void setBookingTypeId(Integer value) {
        setAttributeInternal(BOOKINGTYPEID, value);
    }

    /**
     * Gets the attribute value for BookingTime, using the alias name BookingTime.
     * @return the value of BookingTime
     */
    public Timestamp getBookingTime() {
        return (Timestamp) getAttributeInternal(BOOKINGTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingTime.
     * @param value value to set the BookingTime
     */
    public void setBookingTime(Timestamp value) {
        setAttributeInternal(BOOKINGTIME, value);
    }

    /**
     * Gets the attribute value for ExpectedTravelTime, using the alias name ExpectedTravelTime.
     * @return the value of ExpectedTravelTime
     */
    public Timestamp getExpectedTravelTime() {
        return (Timestamp) getAttributeInternal(EXPECTEDTRAVELTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpectedTravelTime.
     * @param value value to set the ExpectedTravelTime
     */
    public void setExpectedTravelTime(Timestamp value) {
        setAttributeInternal(EXPECTEDTRAVELTIME, value);
    }

    /**
     * Gets the attribute value for Destination, using the alias name Destination.
     * @return the value of Destination
     */
    public String getDestination() {
        return (String) getAttributeInternal(DESTINATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Destination.
     * @param value value to set the Destination
     */
    public void setDestination(String value) {
        setAttributeInternal(DESTINATION, value);
    }

    /**
     * Gets the attribute value for BookingForUserId, using the alias name BookingForUserId.
     * @return the value of BookingForUserId
     */
    public Integer getBookingForUserId() {
        return (Integer) getAttributeInternal(BOOKINGFORUSERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingForUserId.
     * @param value value to set the BookingForUserId
     */
    public void setBookingForUserId(Integer value) {
        setAttributeInternal(BOOKINGFORUSERID, value);
    }

    /**
     * Gets the attribute value for ItemsTransportedId, using the alias name ItemsTransportedId.
     * @return the value of ItemsTransportedId
     */
    public Integer getItemsTransportedId() {
        return (Integer) getAttributeInternal(ITEMSTRANSPORTEDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemsTransportedId.
     * @param value value to set the ItemsTransportedId
     */
    public void setItemsTransportedId(Integer value) {
        setAttributeInternal(ITEMSTRANSPORTEDID, value);
    }

    /**
     * Gets the attribute value for BookingStaffComments, using the alias name BookingStaffComments.
     * @return the value of BookingStaffComments
     */
    public String getBookingStaffComments() {
        return (String) getAttributeInternal(BOOKINGSTAFFCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingStaffComments.
     * @param value value to set the BookingStaffComments
     */
    public void setBookingStaffComments(String value) {
        setAttributeInternal(BOOKINGSTAFFCOMMENTS, value);
    }

    /**
     * Gets the attribute value for BookingActionTime, using the alias name BookingActionTime.
     * @return the value of BookingActionTime
     */
    public Timestamp getBookingActionTime() {
        return (Timestamp) getAttributeInternal(BOOKINGACTIONTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingActionTime.
     * @param value value to set the BookingActionTime
     */
    public void setBookingActionTime(Timestamp value) {
        setAttributeInternal(BOOKINGACTIONTIME, value);
    }

    /**
     * Gets the attribute value for ApprovingStaffComments, using the alias name ApprovingStaffComments.
     * @return the value of ApprovingStaffComments
     */
    public String getApprovingStaffComments() {
        return (String) getAttributeInternal(APPROVINGSTAFFCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovingStaffComments.
     * @param value value to set the ApprovingStaffComments
     */
    public void setApprovingStaffComments(String value) {
        setAttributeInternal(APPROVINGSTAFFCOMMENTS, value);
    }

    /**
     * Gets the attribute value for BookingStatusId, using the alias name BookingStatusId.
     * @return the value of BookingStatusId
     */
    public Integer getBookingStatusId() {
        return (Integer) getAttributeInternal(BOOKINGSTATUSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingStatusId.
     * @param value value to set the BookingStatusId
     */
    public void setBookingStatusId(Integer value) {
        setAttributeInternal(BOOKINGSTATUSID, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public Integer getIsActive() {
        return (Integer) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(Integer value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for IdString, using the alias name IdString.
     * @return the value of IdString
     */
    public String getIdString() {
        return (String) getAttributeInternal(IDSTRING);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdString.
     * @param value value to set the IdString
     */
    public void setIdString(String value) {
        setAttributeInternal(IDSTRING, value);
    }

    /**
     * Gets the attribute value for ProviderId, using the alias name ProviderId.
     * @return the value of ProviderId
     */
    public String getProviderId() {
        return (String) getAttributeInternal(PROVIDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProviderId.
     * @param value value to set the ProviderId
     */
    public void setProviderId(String value) {
        setAttributeInternal(PROVIDERID, value);
    }

    /**
     * Gets the attribute value for TripEndTime, using the alias name TripEndTime.
     * @return the value of TripEndTime
     */
    public Timestamp getTripEndTime() {
        return (Timestamp) getAttributeInternal(TRIPENDTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TripEndTime.
     * @param value value to set the TripEndTime
     */
    public void setTripEndTime(Timestamp value) {
        setAttributeInternal(TRIPENDTIME, value);
    }

    /**
     * Gets the attribute value for AllocatedDriverId, using the alias name AllocatedDriverId.
     * @return the value of AllocatedDriverId
     */
    public Integer getAllocatedDriverId() {
        return (Integer) getAttributeInternal(ALLOCATEDDRIVERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllocatedDriverId.
     * @param value value to set the AllocatedDriverId
     */
    public void setAllocatedDriverId(Integer value) {
        setAttributeInternal(ALLOCATEDDRIVERID, value);
    }

    /**
     * Gets the attribute value for AllocatedVehicleId, using the alias name AllocatedVehicleId.
     * @return the value of AllocatedVehicleId
     */
    public Integer getAllocatedVehicleId() {
        return (Integer) getAttributeInternal(ALLOCATEDVEHICLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllocatedVehicleId.
     * @param value value to set the AllocatedVehicleId
     */
    public void setAllocatedVehicleId(Integer value) {
        setAttributeInternal(ALLOCATEDVEHICLEID, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBookings() {
        return (RowIterator) getAttributeInternal(BOOKINGS);
    }

    /**
     * @return the associated entity BookingsImpl.
     */
    public BookingsImpl getUserIdBookings() {
        return (BookingsImpl) getAttributeInternal(USERIDBOOKINGS);
    }

    /**
     * Sets <code>value</code> as the associated entity BookingsImpl.
     */
    public void setUserIdBookings(BookingsImpl value) {
        setAttributeInternal(USERIDBOOKINGS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBookings1() {
        return (RowIterator) getAttributeInternal(BOOKINGS1);
    }

    /**
     * @return the associated entity BookingsImpl.
     */
    public BookingsImpl getItemsTransportedIdBookings() {
        return (BookingsImpl) getAttributeInternal(ITEMSTRANSPORTEDIDBOOKINGS);
    }

    /**
     * Sets <code>value</code> as the associated entity BookingsImpl.
     */
    public void setItemsTransportedIdBookings(BookingsImpl value) {
        setAttributeInternal(ITEMSTRANSPORTEDIDBOOKINGS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBookings2() {
        return (RowIterator) getAttributeInternal(BOOKINGS2);
    }

    /**
     * @return the associated entity BookingsImpl.
     */
    public BookingsImpl getBookingTypeIdBookings() {
        return (BookingsImpl) getAttributeInternal(BOOKINGTYPEIDBOOKINGS);
    }

    /**
     * Sets <code>value</code> as the associated entity BookingsImpl.
     */
    public void setBookingTypeIdBookings(BookingsImpl value) {
        setAttributeInternal(BOOKINGTYPEIDBOOKINGS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBookings3() {
        return (RowIterator) getAttributeInternal(BOOKINGS3);
    }

    /**
     * @return the associated entity BookingsImpl.
     */
    public BookingsImpl getBookingStatusIdBookings() {
        return (BookingsImpl) getAttributeInternal(BOOKINGSTATUSIDBOOKINGS);
    }

    /**
     * Sets <code>value</code> as the associated entity BookingsImpl.
     */
    public void setBookingStatusIdBookings(BookingsImpl value) {
        setAttributeInternal(BOOKINGSTATUSIDBOOKINGS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingStatus() {
        return (EntityImpl) getAttributeInternal(BOOKINGSTATUS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingStatus(EntityImpl value) {
        setAttributeInternal(BOOKINGSTATUS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingTypes() {
        return (EntityImpl) getAttributeInternal(BOOKINGTYPES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingTypes(EntityImpl value) {
        setAttributeInternal(BOOKINGTYPES, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingStatus1() {
        return (EntityImpl) getAttributeInternal(BOOKINGSTATUS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingStatus1(EntityImpl value) {
        setAttributeInternal(BOOKINGSTATUS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingTypes1() {
        return (EntityImpl) getAttributeInternal(BOOKINGTYPES1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingTypes1(EntityImpl value) {
        setAttributeInternal(BOOKINGTYPES1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingStatus2() {
        return (EntityImpl) getAttributeInternal(BOOKINGSTATUS2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingStatus2(EntityImpl value) {
        setAttributeInternal(BOOKINGSTATUS2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingTypes2() {
        return (EntityImpl) getAttributeInternal(BOOKINGTYPES2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingTypes2(EntityImpl value) {
        setAttributeInternal(BOOKINGTYPES2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingStatus3() {
        return (EntityImpl) getAttributeInternal(BOOKINGSTATUS3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingStatus3(EntityImpl value) {
        setAttributeInternal(BOOKINGSTATUS3, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBookingTypes3() {
        return (EntityImpl) getAttributeInternal(BOOKINGTYPES3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBookingTypes3(EntityImpl value) {
        setAttributeInternal(BOOKINGTYPES3, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDrivers() {
        return (EntityImpl) getAttributeInternal(DRIVERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDrivers(EntityImpl value) {
        setAttributeInternal(DRIVERS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDrivers1() {
        return (EntityImpl) getAttributeInternal(DRIVERS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDrivers1(EntityImpl value) {
        setAttributeInternal(DRIVERS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDrivers2() {
        return (EntityImpl) getAttributeInternal(DRIVERS2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDrivers2(EntityImpl value) {
        setAttributeInternal(DRIVERS2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDrivers3() {
        return (EntityImpl) getAttributeInternal(DRIVERS3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDrivers3(EntityImpl value) {
        setAttributeInternal(DRIVERS3, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRefills() {
        return (EntityImpl) getAttributeInternal(REFILLS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRefills(EntityImpl value) {
        setAttributeInternal(REFILLS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRefills1() {
        return (EntityImpl) getAttributeInternal(REFILLS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRefills1(EntityImpl value) {
        setAttributeInternal(REFILLS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRefills2() {
        return (EntityImpl) getAttributeInternal(REFILLS2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRefills2(EntityImpl value) {
        setAttributeInternal(REFILLS2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRefills3() {
        return (EntityImpl) getAttributeInternal(REFILLS3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRefills3(EntityImpl value) {
        setAttributeInternal(REFILLS3, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getRefills4() {
        return (RowIterator) getAttributeInternal(REFILLS4);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRoles() {
        return (EntityImpl) getAttributeInternal(ROLES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRoles(EntityImpl value) {
        setAttributeInternal(ROLES, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRoles1() {
        return (EntityImpl) getAttributeInternal(ROLES1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRoles1(EntityImpl value) {
        setAttributeInternal(ROLES1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRoles2() {
        return (EntityImpl) getAttributeInternal(ROLES2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRoles2(EntityImpl value) {
        setAttributeInternal(ROLES2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getRoles3() {
        return (EntityImpl) getAttributeInternal(ROLES3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setRoles3(EntityImpl value) {
        setAttributeInternal(ROLES3, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTransportItems() {
        return (EntityImpl) getAttributeInternal(TRANSPORTITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTransportItems(EntityImpl value) {
        setAttributeInternal(TRANSPORTITEMS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTransportItems1() {
        return (EntityImpl) getAttributeInternal(TRANSPORTITEMS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTransportItems1(EntityImpl value) {
        setAttributeInternal(TRANSPORTITEMS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTransportItems2() {
        return (EntityImpl) getAttributeInternal(TRANSPORTITEMS2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTransportItems2(EntityImpl value) {
        setAttributeInternal(TRANSPORTITEMS2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTransportItems3() {
        return (EntityImpl) getAttributeInternal(TRANSPORTITEMS3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTransportItems3(EntityImpl value) {
        setAttributeInternal(TRANSPORTITEMS3, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTrips() {
        return (EntityImpl) getAttributeInternal(TRIPS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTrips(EntityImpl value) {
        setAttributeInternal(TRIPS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTrips1() {
        return (EntityImpl) getAttributeInternal(TRIPS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTrips1(EntityImpl value) {
        setAttributeInternal(TRIPS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTrips2() {
        return (EntityImpl) getAttributeInternal(TRIPS2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTrips2(EntityImpl value) {
        setAttributeInternal(TRIPS2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getTrips3() {
        return (EntityImpl) getAttributeInternal(TRIPS3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setTrips3(EntityImpl value) {
        setAttributeInternal(TRIPS3, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTrips4() {
        return (RowIterator) getAttributeInternal(TRIPS4);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTrips5() {
        return (RowIterator) getAttributeInternal(TRIPS5);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTrips6() {
        return (RowIterator) getAttributeInternal(TRIPS6);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUnits() {
        return (EntityImpl) getAttributeInternal(UNITS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUnits(EntityImpl value) {
        setAttributeInternal(UNITS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUnits1() {
        return (EntityImpl) getAttributeInternal(UNITS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUnits1(EntityImpl value) {
        setAttributeInternal(UNITS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUnits2() {
        return (EntityImpl) getAttributeInternal(UNITS2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUnits2(EntityImpl value) {
        setAttributeInternal(UNITS2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUnits3() {
        return (EntityImpl) getAttributeInternal(UNITS3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUnits3(EntityImpl value) {
        setAttributeInternal(UNITS3, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUsers() {
        return (EntityImpl) getAttributeInternal(USERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUsers(EntityImpl value) {
        setAttributeInternal(USERS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUsers1() {
        return (EntityImpl) getAttributeInternal(USERS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUsers1(EntityImpl value) {
        setAttributeInternal(USERS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUsers2() {
        return (EntityImpl) getAttributeInternal(USERS2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUsers2(EntityImpl value) {
        setAttributeInternal(USERS2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getUsers3() {
        return (EntityImpl) getAttributeInternal(USERS3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setUsers3(EntityImpl value) {
        setAttributeInternal(USERS3, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getUsers4() {
        return (RowIterator) getAttributeInternal(USERS4);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getUsers5() {
        return (RowIterator) getAttributeInternal(USERS5);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getVehicles() {
        return (EntityImpl) getAttributeInternal(VEHICLES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setVehicles(EntityImpl value) {
        setAttributeInternal(VEHICLES, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getVehicles1() {
        return (EntityImpl) getAttributeInternal(VEHICLES1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setVehicles1(EntityImpl value) {
        setAttributeInternal(VEHICLES1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getVehicles2() {
        return (EntityImpl) getAttributeInternal(VEHICLES2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setVehicles2(EntityImpl value) {
        setAttributeInternal(VEHICLES2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getVehicles3() {
        return (EntityImpl) getAttributeInternal(VEHICLES3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setVehicles3(EntityImpl value) {
        setAttributeInternal(VEHICLES3, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmailProperties() {
        return (EntityImpl) getAttributeInternal(EMAILPROPERTIES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmailProperties(EntityImpl value) {
        setAttributeInternal(EMAILPROPERTIES, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmailProperties1() {
        return (EntityImpl) getAttributeInternal(EMAILPROPERTIES1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmailProperties1(EntityImpl value) {
        setAttributeInternal(EMAILPROPERTIES1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmailProperties2() {
        return (EntityImpl) getAttributeInternal(EMAILPROPERTIES2);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmailProperties2(EntityImpl value) {
        setAttributeInternal(EMAILPROPERTIES2, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmailProperties3() {
        return (EntityImpl) getAttributeInternal(EMAILPROPERTIES3);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmailProperties3(EntityImpl value) {
        setAttributeInternal(EMAILPROPERTIES3, value);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer id) {
        return new Key(new Object[] { id });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */

    @Override
    protected void doDML(int operation, TransactionEvent e) {
        final String BOOKING_STATUS_ID = "BookingStatusId";
        String bookedById = "";
        String bookingForId = "";
        String emailBody = "";
        String emailSubject = "";
        String emailToAddress = "";
        String emailCcAddress = "";
        int userId = 0;
        try{
          //  if(runDoDML){
            usersViewImpl = new UsersViewImpl();
            emailPropertiesViewImpl = new EmailPropertiesViewImpl();
            int indexOf = this.getAttributeIndexOf("UserId");
            //Get bookedById
            int loggedUserId = UsersViewImpl.getLoggedinUserId();
            bookedById = getPostedAttribute(indexOf) == null ? UsersViewImpl.getLoggedinUserId() + "" : getPostedAttribute(indexOf).toString();
            //Set the userId for the current createInsert() row
            this.setUserId(loggedUserId);
            //Get bookingForId
            bookingForId = getPostedAttribute(this.getAttributeIndexOf("BookingForUserId")).toString();
            //Get emailTo address
            emailToAddress = usersViewImpl.getEmail(bookedById);
            //Get emailCc address
            emailCcAddress = usersViewImpl.getEmail(bookingForId);
            // Get posted value of BookingStatusId attribute
            Object postedBookingStatusId = getPostedAttribute(this.getAttributeIndexOf(BOOKING_STATUS_ID));
            // Get value of BookingStatusId before re-posting
            Object bookingStatusId = this.getAttribute(BOOKING_STATUS_ID);
            //Booking Status set to Approved
            if (bookingStatusId != null) {
                if (bookingStatusId.equals(2)) {
                    //Send booking approved e-mail
                    emailSubject = emailPropertiesViewImpl.getBookingApprovedSubject();
                    emailBody = emailPropertiesViewImpl.getBookingApprovedBody();
                    //fleet.view.backing.SendEmail.
                    SendEmail.send(emailToAddress, emailCcAddress, emailSubject, emailBody);
                    //Booking Status set to Disapproved
                } else if (bookingStatusId.equals(3)) {
                    emailSubject = emailPropertiesViewImpl.getBookingNotApprovedSubject();
                    emailBody = emailPropertiesViewImpl.getBookingNotApprovedBody();
                    SendEmail.send(emailToAddress, emailCcAddress, emailSubject, emailBody);
                }
            }
            // finally re-post by calling super.doDML()
            super.doDML(operation, e);
      //  }
       // }
        } catch (Exception exception) {
            exception.printStackTrace();       
    }
    }

 //   @Override
 //   public void beforeCommit(TransactionEvent event) {

 //   }


    public static void setRunDoDML(boolean runDoDML) {
        BookingsImpl.runDoDML = runDoDML;
    }

    public static boolean isRunDoDML() {
        return runDoDML;
    }
}

