package fleet.model;

import java.sql.ResultSet;
import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.client.Configuration;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 26 11:17:17 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookingsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BookingsViewImpl() {
    }

    /**
     * Returns the variable value for bind_timezone.
     * @return variable value for bind_timezone
     */
    public String getbind_timezone() {
        return (String) ensureVariableManager().getVariableValue("bind_timezone");
    }

    /**
     * Sets <code>value</code> for variable bind_timezone.
     * @param value value to bind as bind_timezone
     */
    public void setbind_timezone(String value) {
        ensureVariableManager().setVariableValue("bind_timezone", value);
    }

    /**
     * Returns the variable value for bind_start_time.
     * @return variable value for bind_start_time
     */
    public Timestamp getbind_start_time() {
        return (Timestamp) ensureVariableManager().getVariableValue("bind_start_time");
    }

    /**
     * Sets <code>value</code> for variable bind_start_time.
     * @param value value to bind as bind_start_time
     */
    public void setbind_start_time(Timestamp value) {
        ensureVariableManager().setVariableValue("bind_start_time", value);
    }

    /**
     * Returns the variable value for bind_end_time.
     * @return variable value for bind_end_time
     */
    public Timestamp getbind_end_time() {
        return (Timestamp) ensureVariableManager().getVariableValue("bind_end_time");
    }

    /**
     * Sets <code>value</code> for variable bind_end_time.
     * @param value value to bind as bind_end_time
     */
    public void setbind_end_time(Timestamp value) {
        ensureVariableManager().setVariableValue("bind_end_time", value);
    }

    /**
     * executeQueryForCollection - for custom java data source support.
     */
    @Override
    protected void executeQueryForCollection(Object qc, Object[] params, int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - for custom java data source support.
     */
    @Override
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - for custom java data source support.
     */
    @Override
    protected ViewRowImpl createRowFromResultSet(Object qc, ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - for custom java data source support.
     */
    @Override
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    /**
     * getCappedQueryHitCount - for custom java data source support.
     */
    @Override
    public long getCappedQueryHitCount(ViewRowSetImpl viewRowSet, Row[] masterRows, long oldCap, long cap) {
        long value = super.getCappedQueryHitCount(viewRowSet, masterRows, oldCap, cap);
        return value;
    }
    
    //Create booking
    public int createBooking(int userId, int bookingForUserId, int bookingTypeId, int itemsTransportedId, java.util.Date expectedTravelTime, java.util.Date tripEndTime, String destination, String bookingStaffComments){
        //boolean bookingCreated = false;
        ApplicationModule appMod=null;
        BookingsViewImpl vo;       
        int bookingId = 0;
        try{
            appMod = Configuration.createRootApplicationModule("fleet.model.AppModuleFleet","AppModuleFleetLocal");
            vo = (BookingsViewImpl)appMod.findViewObject("BookingsView1");   
            Row row = vo.createRow();
            row.setAttribute("UserId", userId);
            row.setAttribute("BookingForUserId", bookingForUserId);
            row.setAttribute("BookingTypeId", bookingTypeId);
            row.setAttribute("ExpectedTravelTime", expectedTravelTime);
            row.setAttribute("TripEndTime", tripEndTime);
            row.setAttribute("Destination", destination);
            row.setAttribute("ItemsTransportedId", itemsTransportedId);
            row.setAttribute("BookingStaffComments", bookingStaffComments);
            appMod.getTransaction().commit();
            vo.executeQuery();
            Row last = vo.last();            
            String idString = last.getKey() != null ? last.getKey().toString().replace("oracle.jbo.Key[", "") : "0";
            idString = idString.replace(" ]", "");
            //Update idString column with row prmary key (id value) --  VERY IMPORTANT OPERATION
            last.setAttribute("IdString", idString);
            appMod.getTransaction().commit();
            vo.executeQuery(); 
            bookingId = Integer.parseInt(idString);
          //  bookingCreated = true;
        }catch(Exception exception){
            System.err.println("Error creating booking in createBooking() method");
          //  bookingCreated = false;
            exception.printStackTrace();
        }finally{
            if(appMod != null){
                Configuration.releaseRootApplicationModule(appMod, false);                      
            }
            vo = null;
        }
        return bookingId;
    } 
}

