package fleet.model;

import fleet.model.common.BookingsPendingViewRow;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 14 16:56:48 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookingsPendingViewRowImpl extends ViewRowImpl implements BookingsPendingViewRow {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        UserId,
        BookingTypeId,
        BookingTime,
        ExpectedTravelTime,
        Destination,
        BookingForUserId,
        ItemsTransportedId,
        BookingStaffComments,
        BookingActionTime,
        ApprovingStaffComments,
        BookingStatusId,
        IsActive,
        TripEndTime,
        ProviderId,
        IdString,
        AllocatedDriverId,
        AllocatedVehicleId,
        VehiclesView1,
        DriversView1,
        BookingStatusView1,
        UsersView1,
        BookingTypesView1,
        TransportItemsView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int BOOKINGTYPEID = AttributesEnum.BookingTypeId.index();
    public static final int BOOKINGTIME = AttributesEnum.BookingTime.index();
    public static final int EXPECTEDTRAVELTIME = AttributesEnum.ExpectedTravelTime.index();
    public static final int DESTINATION = AttributesEnum.Destination.index();
    public static final int BOOKINGFORUSERID = AttributesEnum.BookingForUserId.index();
    public static final int ITEMSTRANSPORTEDID = AttributesEnum.ItemsTransportedId.index();
    public static final int BOOKINGSTAFFCOMMENTS = AttributesEnum.BookingStaffComments.index();
    public static final int BOOKINGACTIONTIME = AttributesEnum.BookingActionTime.index();
    public static final int APPROVINGSTAFFCOMMENTS = AttributesEnum.ApprovingStaffComments.index();
    public static final int BOOKINGSTATUSID = AttributesEnum.BookingStatusId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int TRIPENDTIME = AttributesEnum.TripEndTime.index();
    public static final int PROVIDERID = AttributesEnum.ProviderId.index();
    public static final int IDSTRING = AttributesEnum.IdString.index();
    public static final int ALLOCATEDDRIVERID = AttributesEnum.AllocatedDriverId.index();
    public static final int ALLOCATEDVEHICLEID = AttributesEnum.AllocatedVehicleId.index();
    public static final int VEHICLESVIEW1 = AttributesEnum.VehiclesView1.index();
    public static final int DRIVERSVIEW1 = AttributesEnum.DriversView1.index();
    public static final int BOOKINGSTATUSVIEW1 = AttributesEnum.BookingStatusView1.index();
    public static final int USERSVIEW1 = AttributesEnum.UsersView1.index();
    public static final int BOOKINGTYPESVIEW1 = AttributesEnum.BookingTypesView1.index();
    public static final int TRANSPORTITEMSVIEW1 = AttributesEnum.TransportItemsView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BookingsPendingViewRowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Gets the attribute value for the calculated attribute BookingTypeId.
     * @return the BookingTypeId
     */
    public Integer getBookingTypeId() {
        return (Integer) getAttributeInternal(BOOKINGTYPEID);
    }

    /**
     * Gets the attribute value for the calculated attribute BookingTime.
     * @return the BookingTime
     */
    public Timestamp getBookingTime() {
        return (Timestamp) getAttributeInternal(BOOKINGTIME);
    }

    /**
     * Gets the attribute value for the calculated attribute ExpectedTravelTime.
     * @return the ExpectedTravelTime
     */
    public Timestamp getExpectedTravelTime() {
        return (Timestamp) getAttributeInternal(EXPECTEDTRAVELTIME);
    }

    /**
     * Gets the attribute value for the calculated attribute Destination.
     * @return the Destination
     */
    public String getDestination() {
        return (String) getAttributeInternal(DESTINATION);
    }

    /**
     * Gets the attribute value for the calculated attribute BookingForUserId.
     * @return the BookingForUserId
     */
    public Integer getBookingForUserId() {
        return (Integer) getAttributeInternal(BOOKINGFORUSERID);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemsTransportedId.
     * @return the ItemsTransportedId
     */
    public Integer getItemsTransportedId() {
        return (Integer) getAttributeInternal(ITEMSTRANSPORTEDID);
    }

    /**
     * Gets the attribute value for the calculated attribute BookingStaffComments.
     * @return the BookingStaffComments
     */
    public String getBookingStaffComments() {
        return (String) getAttributeInternal(BOOKINGSTAFFCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BookingStaffComments.
     * @param value value to set the  BookingStaffComments
     */
    public void setBookingStaffComments(String value) {
        setAttributeInternal(BOOKINGSTAFFCOMMENTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BookingActionTime.
     * @return the BookingActionTime
     */
    public Timestamp getBookingActionTime() {
        return (Timestamp) getAttributeInternal(BOOKINGACTIONTIME);
    }

    /**
     * Gets the attribute value for the calculated attribute ApprovingStaffComments.
     * @return the ApprovingStaffComments
     */
    public String getApprovingStaffComments() {
        return (String) getAttributeInternal(APPROVINGSTAFFCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApprovingStaffComments.
     * @param value value to set the  ApprovingStaffComments
     */
    public void setApprovingStaffComments(String value) {
        setAttributeInternal(APPROVINGSTAFFCOMMENTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BookingStatusId.
     * @return the BookingStatusId
     */
    public Integer getBookingStatusId() {
        return (Integer) getAttributeInternal(BOOKINGSTATUSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BookingStatusId.
     * @param value value to set the  BookingStatusId
     */
    public void setBookingStatusId(Integer value) {
        setAttributeInternal(BOOKINGSTATUSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsActive.
     * @return the IsActive
     */
    public Integer getIsActive() {
        return (Integer) getAttributeInternal(ISACTIVE);
    }

    /**
     * Gets the attribute value for the calculated attribute TripEndTime.
     * @return the TripEndTime
     */
    public Timestamp getTripEndTime() {
        return (Timestamp) getAttributeInternal(TRIPENDTIME);
    }

    /**
     * Gets the attribute value for the calculated attribute ProviderId.
     * @return the ProviderId
     */
    public String getProviderId() {
        return (String) getAttributeInternal(PROVIDERID);
    }

    /**
     * Gets the attribute value for the calculated attribute IdString.
     * @return the IdString
     */
    public String getIdString() {
        return (String) getAttributeInternal(IDSTRING);
    }

    /**
     * Gets the attribute value for the calculated attribute AllocatedDriverId.
     * @return the AllocatedDriverId
     */
    public Integer getAllocatedDriverId() {
        return (Integer) getAttributeInternal(ALLOCATEDDRIVERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AllocatedDriverId.
     * @param value value to set the  AllocatedDriverId
     */
    public void setAllocatedDriverId(Integer value) {
        setAttributeInternal(ALLOCATEDDRIVERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AllocatedVehicleId.
     * @return the AllocatedVehicleId
     */
    public Integer getAllocatedVehicleId() {
        return (Integer) getAttributeInternal(ALLOCATEDVEHICLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AllocatedVehicleId.
     * @param value value to set the  AllocatedVehicleId
     */
    public void setAllocatedVehicleId(Integer value) {
        setAttributeInternal(ALLOCATEDVEHICLEID, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> VehiclesView1.
     */
    public RowSet getVehiclesView1() {
        return (RowSet) getAttributeInternal(VEHICLESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DriversView1.
     */
    public RowSet getDriversView1() {
        return (RowSet) getAttributeInternal(DRIVERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BookingStatusView1.
     */
    public RowSet getBookingStatusView1() {
        return (RowSet) getAttributeInternal(BOOKINGSTATUSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UsersView1.
     */
    public RowSet getUsersView1() {
        return (RowSet) getAttributeInternal(USERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BookingTypesView1.
     */
    public RowSet getBookingTypesView1() {
        return (RowSet) getAttributeInternal(BOOKINGTYPESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TransportItemsView1.
     */
    public RowSet getTransportItemsView1() {
        return (RowSet) getAttributeInternal(TRANSPORTITEMSVIEW1);
    }
}

