package fleet.model;

import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 15 08:14:49 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookingsUnProcessedImpl extends BookingsViewImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BookingsUnProcessedImpl() {
    }
}

