package fleet.model;

import fleet.model.common.DriversViewRow;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 02 09:52:21 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DriversViewRowImpl extends ViewRowImpl implements DriversViewRow {


    public static final int ENTITY_DRIVERS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        FirstName,
        LastName,
        OtherNames,
        Gender,
        TelephoneMobile,
        TelephoneOffice,
        Email,
        IsActive,
        Description,
        DriverStatusId,
        BookingsView,
        BookingsView1,
        BookingsView2,
        BookingsView3,
        RefillsView,
        TripsView,
        TripsView1,
        TripsView2,
        UsersView,
        UsersView1,
        DriverStatusView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int OTHERNAMES = AttributesEnum.OtherNames.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int TELEPHONEMOBILE = AttributesEnum.TelephoneMobile.index();
    public static final int TELEPHONEOFFICE = AttributesEnum.TelephoneOffice.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int DRIVERSTATUSID = AttributesEnum.DriverStatusId.index();
    public static final int BOOKINGSVIEW = AttributesEnum.BookingsView.index();
    public static final int BOOKINGSVIEW1 = AttributesEnum.BookingsView1.index();
    public static final int BOOKINGSVIEW2 = AttributesEnum.BookingsView2.index();
    public static final int BOOKINGSVIEW3 = AttributesEnum.BookingsView3.index();
    public static final int REFILLSVIEW = AttributesEnum.RefillsView.index();
    public static final int TRIPSVIEW = AttributesEnum.TripsView.index();
    public static final int TRIPSVIEW1 = AttributesEnum.TripsView1.index();
    public static final int TRIPSVIEW2 = AttributesEnum.TripsView2.index();
    public static final int USERSVIEW = AttributesEnum.UsersView.index();
    public static final int USERSVIEW1 = AttributesEnum.UsersView1.index();
    public static final int DRIVERSTATUSVIEW1 = AttributesEnum.DriverStatusView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DriversViewRowImpl() {
    }

    /**
     * Gets Drivers entity object.
     * @return the Drivers
     */
    public EntityImpl getDrivers() {
        return (EntityImpl) getEntity(ENTITY_DRIVERS);
    }

    /**
     * Gets the attribute value for id using the alias name Id.
     * @return the id
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name Id.
     * @param value value to set the id
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for first_name using the alias name FirstName.
     * @return the first_name
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for first_name using the alias name FirstName.
     * @param value value to set the first_name
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for last_name using the alias name LastName.
     * @return the last_name
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for last_name using the alias name LastName.
     * @param value value to set the last_name
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for other_names using the alias name OtherNames.
     * @return the other_names
     */
    public String getOtherNames() {
        return (String) getAttributeInternal(OTHERNAMES);
    }

    /**
     * Sets <code>value</code> as attribute value for other_names using the alias name OtherNames.
     * @param value value to set the other_names
     */
    public void setOtherNames(String value) {
        setAttributeInternal(OTHERNAMES, value);
    }

    /**
     * Gets the attribute value for gender using the alias name Gender.
     * @return the gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as attribute value for gender using the alias name Gender.
     * @param value value to set the gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for telephone_mobile using the alias name TelephoneMobile.
     * @return the telephone_mobile
     */
    public String getTelephoneMobile() {
        return (String) getAttributeInternal(TELEPHONEMOBILE);
    }

    /**
     * Sets <code>value</code> as attribute value for telephone_mobile using the alias name TelephoneMobile.
     * @param value value to set the telephone_mobile
     */
    public void setTelephoneMobile(String value) {
        setAttributeInternal(TELEPHONEMOBILE, value);
    }

    /**
     * Gets the attribute value for telephone_office using the alias name TelephoneOffice.
     * @return the telephone_office
     */
    public String getTelephoneOffice() {
        return (String) getAttributeInternal(TELEPHONEOFFICE);
    }

    /**
     * Sets <code>value</code> as attribute value for telephone_office using the alias name TelephoneOffice.
     * @param value value to set the telephone_office
     */
    public void setTelephoneOffice(String value) {
        setAttributeInternal(TELEPHONEOFFICE, value);
    }

    /**
     * Gets the attribute value for email using the alias name Email.
     * @return the email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for email using the alias name Email.
     * @param value value to set the email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for is_active using the alias name IsActive.
     * @return the is_active
     */
    public Integer getIsActive() {
        return (Integer) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for is_active using the alias name IsActive.
     * @param value value to set the is_active
     */
    public void setIsActive(Integer value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for description using the alias name Description.
     * @return the description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for description using the alias name Description.
     * @param value value to set the description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for driver_status_id using the alias name DriverStatusId.
     * @return the driver_status_id
     */
    public Integer getDriverStatusId() {
        return (Integer) getAttributeInternal(DRIVERSTATUSID);
    }

    /**
     * Sets <code>value</code> as attribute value for driver_status_id using the alias name DriverStatusId.
     * @param value value to set the driver_status_id
     */
    public void setDriverStatusId(Integer value) {
        setAttributeInternal(DRIVERSTATUSID, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView.
     */
    public RowIterator getBookingsView() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView1.
     */
    public RowIterator getBookingsView1() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView2.
     */
    public RowIterator getBookingsView2() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW2);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView3.
     */
    public RowIterator getBookingsView3() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW3);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RefillsView.
     */
    public RowIterator getRefillsView() {
        return (RowIterator) getAttributeInternal(REFILLSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView.
     */
    public RowIterator getTripsView() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView1.
     */
    public RowIterator getTripsView1() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView2.
     */
    public RowIterator getTripsView2() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW2);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UsersView.
     */
    public RowIterator getUsersView() {
        return (RowIterator) getAttributeInternal(USERSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UsersView1.
     */
    public RowIterator getUsersView1() {
        return (RowIterator) getAttributeInternal(USERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DriverStatusView1.
     */
    public RowSet getDriverStatusView1() {
        return (RowSet) getAttributeInternal(DRIVERSTATUSVIEW1);
    }
}

