package fleet.model;

import fleet.model.common.TripPassengersViewRow;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 14:52:48 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TripPassengersViewRowImpl extends ViewRowImpl implements TripPassengersViewRow {


    public static final int ENTITY_TRIPPASSENGERS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        BookingId,
        UserId,
        OnTrip,
        TripJoiningTime;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int BOOKINGID = AttributesEnum.BookingId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int ONTRIP = AttributesEnum.OnTrip.index();
    public static final int TRIPJOININGTIME = AttributesEnum.TripJoiningTime.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TripPassengersViewRowImpl() {
    }

    /**
     * Gets TripPassengers entity object.
     * @return the TripPassengers
     */
    public EntityImpl getTripPassengers() {
        return (EntityImpl) getEntity(ENTITY_TRIPPASSENGERS);
    }

    /**
     * Gets the attribute value for id using the alias name Id.
     * @return the id
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name Id.
     * @param value value to set the id
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for booking_id using the alias name BookingId.
     * @return the booking_id
     */
    public Integer getBookingId() {
        return (Integer) getAttributeInternal(BOOKINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for booking_id using the alias name BookingId.
     * @param value value to set the booking_id
     */
    public void setBookingId(Integer value) {
        setAttributeInternal(BOOKINGID, value);
    }

    /**
     * Gets the attribute value for user_id using the alias name UserId.
     * @return the user_id
     */
    public Integer getUserId() {
        return (Integer) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for user_id using the alias name UserId.
     * @param value value to set the user_id
     */
    public void setUserId(Integer value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for on_trip using the alias name OnTrip.
     * @return the on_trip
     */
    public Integer getOnTrip() {
        return (Integer) getAttributeInternal(ONTRIP);
    }

    /**
     * Sets <code>value</code> as attribute value for on_trip using the alias name OnTrip.
     * @param value value to set the on_trip
     */
    public void setOnTrip(Integer value) {
        setAttributeInternal(ONTRIP, value);
    }

    /**
     * Gets the attribute value for trip_joining_time using the alias name TripJoiningTime.
     * @return the trip_joining_time
     */
    public Timestamp getTripJoiningTime() {
        return (Timestamp) getAttributeInternal(TRIPJOININGTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for trip_joining_time using the alias name TripJoiningTime.
     * @param value value to set the trip_joining_time
     */
    public void setTripJoiningTime(Timestamp value) {
        setAttributeInternal(TRIPJOININGTIME, value);
    }
}

