package fleet.model;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 10 10:54:02 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UnprocessedBookingsRowImpl extends BookingsViewRowImpl {

    public static final int MAXUSAGECONST = 3;

    /**
     * This is the default constructor (do not remove).
     */
    public UnprocessedBookingsRowImpl() {
    }
}

