package fleet.model;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 30 15:55:05 EAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsersViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_USERS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        FirstName,
        LastName,
        OtherName,
        UnitId,
        Gender,
        Email,
        TelephoneMobile,
        TelephoneOffice,
        RoleId,
        IsActive,
        Description,
        IdString,
        PassWord,
        Username,
        TripsView,
        TripsView1,
        TripsView2,
        RefillsView,
        BookingsView,
        BookingsView1,
        BookingsView2,
        BookingsView3,
        UsersView,
        UsersView1,
        UsersView2,
        RolesView1,
        UnitsView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int OTHERNAME = AttributesEnum.OtherName.index();
    public static final int UNITID = AttributesEnum.UnitId.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int TELEPHONEMOBILE = AttributesEnum.TelephoneMobile.index();
    public static final int TELEPHONEOFFICE = AttributesEnum.TelephoneOffice.index();
    public static final int ROLEID = AttributesEnum.RoleId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int IDSTRING = AttributesEnum.IdString.index();
    public static final int PASSWORD = AttributesEnum.PassWord.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int TRIPSVIEW = AttributesEnum.TripsView.index();
    public static final int TRIPSVIEW1 = AttributesEnum.TripsView1.index();
    public static final int TRIPSVIEW2 = AttributesEnum.TripsView2.index();
    public static final int REFILLSVIEW = AttributesEnum.RefillsView.index();
    public static final int BOOKINGSVIEW = AttributesEnum.BookingsView.index();
    public static final int BOOKINGSVIEW1 = AttributesEnum.BookingsView1.index();
    public static final int BOOKINGSVIEW2 = AttributesEnum.BookingsView2.index();
    public static final int BOOKINGSVIEW3 = AttributesEnum.BookingsView3.index();
    public static final int USERSVIEW = AttributesEnum.UsersView.index();
    public static final int USERSVIEW1 = AttributesEnum.UsersView1.index();
    public static final int USERSVIEW2 = AttributesEnum.UsersView2.index();
    public static final int ROLESVIEW1 = AttributesEnum.RolesView1.index();
    public static final int UNITSVIEW1 = AttributesEnum.UnitsView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UsersViewRowImpl() {
    }

    /**
     * Gets Users entity object.
     * @return the Users
     */
    public EntityImpl getUsers() {
        return (EntityImpl) getEntity(ENTITY_USERS);
    }

    /**
     * Gets the attribute value for id using the alias name Id.
     * @return the id
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name Id.
     * @param value value to set the id
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for first_name using the alias name FirstName.
     * @return the first_name
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for first_name using the alias name FirstName.
     * @param value value to set the first_name
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for last_name using the alias name LastName.
     * @return the last_name
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for last_name using the alias name LastName.
     * @param value value to set the last_name
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for other_name using the alias name OtherName.
     * @return the other_name
     */
    public String getOtherName() {
        return (String) getAttributeInternal(OTHERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for other_name using the alias name OtherName.
     * @param value value to set the other_name
     */
    public void setOtherName(String value) {
        setAttributeInternal(OTHERNAME, value);
    }

    /**
     * Gets the attribute value for unit_id using the alias name UnitId.
     * @return the unit_id
     */
    public Integer getUnitId() {
        return (Integer) getAttributeInternal(UNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for unit_id using the alias name UnitId.
     * @param value value to set the unit_id
     */
    public void setUnitId(Integer value) {
        setAttributeInternal(UNITID, value);
    }

    /**
     * Gets the attribute value for gender using the alias name Gender.
     * @return the gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as attribute value for gender using the alias name Gender.
     * @param value value to set the gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for email using the alias name Email.
     * @return the email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for email using the alias name Email.
     * @param value value to set the email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for telephone_mobile using the alias name TelephoneMobile.
     * @return the telephone_mobile
     */
    public String getTelephoneMobile() {
        return (String) getAttributeInternal(TELEPHONEMOBILE);
    }

    /**
     * Sets <code>value</code> as attribute value for telephone_mobile using the alias name TelephoneMobile.
     * @param value value to set the telephone_mobile
     */
    public void setTelephoneMobile(String value) {
        setAttributeInternal(TELEPHONEMOBILE, value);
    }

    /**
     * Gets the attribute value for telephone_office using the alias name TelephoneOffice.
     * @return the telephone_office
     */
    public String getTelephoneOffice() {
        return (String) getAttributeInternal(TELEPHONEOFFICE);
    }

    /**
     * Sets <code>value</code> as attribute value for telephone_office using the alias name TelephoneOffice.
     * @param value value to set the telephone_office
     */
    public void setTelephoneOffice(String value) {
        setAttributeInternal(TELEPHONEOFFICE, value);
    }

    /**
     * Gets the attribute value for role_id using the alias name RoleId.
     * @return the role_id
     */
    public Integer getRoleId() {
        return (Integer) getAttributeInternal(ROLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for role_id using the alias name RoleId.
     * @param value value to set the role_id
     */
    public void setRoleId(Integer value) {
        setAttributeInternal(ROLEID, value);
    }

    /**
     * Gets the attribute value for is_active using the alias name IsActive.
     * @return the is_active
     */
    public Integer getIsActive() {
        return (Integer) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for is_active using the alias name IsActive.
     * @param value value to set the is_active
     */
    public void setIsActive(Integer value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for description using the alias name Description.
     * @return the description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for description using the alias name Description.
     * @param value value to set the description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for id_string using the alias name IdString.
     * @return the id_string
     */
    public String getIdString() {
        return (String) getAttributeInternal(IDSTRING);
    }

    /**
     * Sets <code>value</code> as attribute value for id_string using the alias name IdString.
     * @param value value to set the id_string
     */
    public void setIdString(String value) {
        setAttributeInternal(IDSTRING, value);
    }

    /**
     * Gets the attribute value for pass_word using the alias name PassWord.
     * @return the pass_word
     */
    public String getPassWord() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for pass_word using the alias name PassWord.
     * @param value value to set the pass_word
     */
    public void setPassWord(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for username using the alias name Username.
     * @return the username
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for username using the alias name Username.
     * @param value value to set the username
     */
    public void setUsername(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView.
     */
    public RowIterator getTripsView() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView1.
     */
    public RowIterator getTripsView1() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TripsView2.
     */
    public RowIterator getTripsView2() {
        return (RowIterator) getAttributeInternal(TRIPSVIEW2);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RefillsView.
     */
    public RowIterator getRefillsView() {
        return (RowIterator) getAttributeInternal(REFILLSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView.
     */
    public RowIterator getBookingsView() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView1.
     */
    public RowIterator getBookingsView1() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView2.
     */
    public RowIterator getBookingsView2() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW2);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BookingsView3.
     */
    public RowIterator getBookingsView3() {
        return (RowIterator) getAttributeInternal(BOOKINGSVIEW3);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UsersView.
     */
    public RowIterator getUsersView() {
        return (RowIterator) getAttributeInternal(USERSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UsersView1.
     */
    public RowIterator getUsersView1() {
        return (RowIterator) getAttributeInternal(USERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UsersView2.
     */
    public RowSet getUsersView2() {
        return (RowSet) getAttributeInternal(USERSVIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RolesView1.
     */
    public RowSet getRolesView1() {
        return (RowSet) getAttributeInternal(ROLESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UnitsView1.
     */
    public RowSet getUnitsView1() {
        return (RowSet) getAttributeInternal(UNITSVIEW1);
    }
}

