package fleet.model.common;

import java.sql.Timestamp;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 14 16:56:51 EAT 2017
// ---------------------------------------------------------------------
public interface BookingsPendingViewRow extends Row {
    Integer getId();

    void setId(Integer value);

    Integer getUserId();

    Integer getBookingTypeId();

    Timestamp getBookingTime();

    Timestamp getExpectedTravelTime();

    String getDestination();

    Integer getBookingForUserId();

    Integer getItemsTransportedId();

    String getBookingStaffComments();

    Timestamp getBookingActionTime();

    String getApprovingStaffComments();

    Integer getBookingStatusId();

    Integer getIsActive();

    Timestamp getTripEndTime();

    String getProviderId();

    String getIdString();

    Integer getAllocatedDriverId();

    Integer getAllocatedVehicleId();
}

