package fleet.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 02 09:52:23 EAT 2017
// ---------------------------------------------------------------------
public interface DriversViewRow extends Row {
    Integer getId();

    void setId(Integer value);

    String getFirstName();

    void setFirstName(String value);

    String getLastName();

    void setLastName(String value);

    String getOtherNames();

    void setOtherNames(String value);

    String getGender();

    void setGender(String value);

    String getTelephoneMobile();

    void setTelephoneMobile(String value);

    String getTelephoneOffice();

    void setTelephoneOffice(String value);

    String getEmail();

    void setEmail(String value);

    Integer getIsActive();

    void setIsActive(Integer value);

    String getDescription();

    void setDescription(String value);

    Integer getDriverStatusId();

    void setDriverStatusId(Integer value);
}

