package fleet.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 08 13:25:43 EAT 2017
// ---------------------------------------------------------------------
public interface EmailPropertiesViewRow extends Row {
    Integer getId();

    void setId(Integer value);

    String getEmailBookingAlertSubject();

    void setEmailBookingAlertSubject(String value);

    String getEmailBookingAlertBody();

    void setEmailBookingAlertBody(String value);

    String getEmailBookingApprovedSubject();

    void setEmailBookingApprovedSubject(String value);

    String getEmailBookingApprovedBody();

    void setEmailBookingApprovedBody(String value);

    String getEmailBookingNotApprovedSubject();

    void setEmailBookingNotApprovedSubject(String value);

    String getEmailBookingNotApprovedBody();

    void setEmailBookingNotApprovedBody(String value);

    Integer getIsActive();

    void setIsActive(Integer value);

    String getComments();

    void setComments(String value);
}

