package fleet.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 14:52:54 EAT 2017
// ---------------------------------------------------------------------
public interface TripPassengersViewRow extends Row {
    Integer getId();

    void setId(Integer value);

    Integer getBookingId();

    void setBookingId(Integer value);

    Integer getUserId();

    void setUserId(Integer value);

    Integer getOnTrip();

    void setOnTrip(Integer value);
}

