package fleet.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 20 09:43:59 EAT 2017
// ---------------------------------------------------------------------
public interface UsersView extends ViewObject {
    int getUserId(String username);
}

